import { Difficulty, GameData } from './types';

export const gameData: GameData[] = [
  // Easy Difficulty
  {
    category: "Colors of the Rainbow",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Red", emoji: "🔴" },
      { text: "Orange", emoji: "🟠" },
      { text: "Yellow", emoji: "🟡" },
      { text: "Green", emoji: "🟢" },
      { text: "Blue", emoji: "🔵" },
      { text: "Indigo", emoji: "🟣" },
      { text: "Violet", emoji: "💜" },
      { text: "Purple", emoji: "🍇" },
      { text: "Pink", emoji: "🌸" },
      { text: "Brown", emoji: "🟤" },
    ],
  },
  {
    category: "Things in a Classroom",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Desk", emoji: "🪑", accepted: ["table"] },
      { text: "Chair", emoji: "🪑", accepted: ["chairs"] },
      { text: "Blackboard", emoji: "칠판", accepted: ["board", "whiteboard", "chalkboard"] },
      { text: "Chalk", emoji: "✍️" },
      { text: "Book", emoji: "📖", accepted: ["books"] },
      { text: "Pencil", emoji: "✏️", accepted: ["pencils"] },
      { text: "Teacher", emoji: "🧑‍🏫", accepted: ["teachers"] },
      { text: "Student", emoji: "🧑‍🎓", accepted: ["students"] },
      { text: "Whiteboard", emoji: "📝" },
      { text: "Computer", emoji: "💻", accepted: ["computers"] },
    ],
  },
  {
    category: "Types of Fruit",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Apple", emoji: "🍎", accepted: ["apples"] },
      { text: "Banana", emoji: "🍌", accepted: ["bananas"] },
      { text: "Orange", emoji: "🍊", accepted: ["oranges"] },
      { text: "Grapes", emoji: "🍇", accepted: ["grape"] },
      { text: "Strawberry", emoji: "🍓", accepted: ["strawberries"] },
      { text: "Watermelon", emoji: "🍉", accepted: ["watermelons"] },
      { text: "Pineapple", emoji: "🍍", accepted: ["pineapples"] },
      { text: "Mango", emoji: "🥭", accepted: ["mangos", "mangoes"] },
      { text: "Blueberry", emoji: "🫐", accepted: ["blueberries"] },
      { text: "Peach", emoji: "🍑", accepted: ["peaches"] },
    ],
  },
  {
    category: "Farm Animals",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Cow", emoji: "🐮", accepted: ["cows"] },
      { text: "Pig", emoji: "🐷", accepted: ["pigs"] },
      { text: "Chicken", emoji: "🐔", accepted: ["chickens"] },
      { text: "Horse", emoji: "🐴", accepted: ["horses"] },
      { text: "Sheep", emoji: "🐑" },
      { text: "Goat", emoji: "🐐", accepted: ["goats"] },
      { text: "Duck", emoji: "🦆", accepted: ["ducks"] },
      { text: "Dog", emoji: "🐶", accepted: ["dogs"] },
      { text: "Cat", emoji: "🐱", accepted: ["cats"] },
      { text: "Donkey", emoji: "🫏", accepted: ["donkeys"] },
    ],
  },
  {
    category: "Things You Wear",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Shirt", emoji: "👕", accepted: ["t-shirt", "tshirt", "tee shirt", "shirts"] },
      { text: "Pants", emoji: "👖" },
      { text: "Shoes", emoji: "👟", accepted: ["shoe"] },
      { text: "Socks", emoji: "🧦", accepted: ["sock"] },
      { text: "Hat", emoji: "🧢", accepted: ["hats"] },
      { text: "Jacket", emoji: "🧥", accepted: ["jackets"] },
      { text: "Dress", emoji: "👗", accepted: ["dresses"] },
      { text: "Skirt", emoji: "🎽", accepted: ["skirts"] },
      { text: "Gloves", emoji: "🧤", accepted: ["glove"] },
      { text: "Scarf", emoji: "🧣", accepted: ["scarves"] },
    ],
  },
  {
    category: "Breakfast Foods",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Cereal", emoji: "🥣" },
      { text: "Eggs", emoji: "🍳", accepted: ["egg"] },
      { text: "Pancakes", emoji: "🥞", accepted: ["pancake"] },
      { text: "Bacon", emoji: "🥓" },
      { text: "Toast", emoji: "🍞" },
      { text: "Sausage", emoji: "🌭", accepted: ["sausages"] },
      { text: "Waffles", emoji: "🧇", accepted: ["waffle"] },
      { text: "Oatmeal", emoji: "🥣" },
      { text: "Yogurt", emoji: "🍦" },
      { text: "Milk", emoji: "🥛" },
    ],
  },
  {
    category: "Zoo Animals",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Lion", emoji: "🦁", accepted: ["lions"] },
        { text: "Tiger", emoji: "🐯", accepted: ["tigers"] },
        { text: "Elephant", emoji: "🐘", accepted: ["elephants"] },
        { text: "Monkey", emoji: "🐵", accepted: ["monkeys"] },
        { text: "Giraffe", emoji: "🦒", accepted: ["giraffes"] },
        { text: "Zebra", emoji: "🦓", accepted: ["zebras"] },
        { text: "Bear", emoji: "🐻", accepted: ["bears"] },
        { text: "Penguin", emoji: "🐧", accepted: ["penguins"] },
        { text: "Kangaroo", emoji: "🦘", accepted: ["kangaroos"] },
        { text: "Hippo", emoji: "🦛", accepted: ["hippos"] },
    ],
  },
  {
    category: "Things in the Sky",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Sun", emoji: "☀️" },
        { text: "Moon", emoji: "🌙" },
        { text: "Stars", emoji: "⭐", accepted: ["star"] },
        { text: "Clouds", emoji: "☁️", accepted: ["cloud"] },
        { text: "Airplane", emoji: "✈️", accepted: ["airplanes", "plane", "planes"] },
        { text: "Bird", emoji: "🐦", accepted: ["birds"] },
        { text: "Kite", emoji: "🪁", accepted: ["kites"] },
        { text: "Rainbow", emoji: "🌈", accepted: ["rainbows"] },
        { text: "Helicopter", emoji: "🚁", accepted: ["helicopters"] },
        { text: "Rocket", emoji: "🚀", accepted: ["rockets"] },
    ],
  },
  {
    category: "Shapes",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Circle", emoji: "⭕", accepted: ["round", "circles"] },
        { text: "Square", emoji: "⬜", accepted: ["squares"] },
        { text: "Triangle", emoji: "🔼", accepted: ["triangles"] },
        { text: "Rectangle", emoji: "▭", accepted: ["rectangles"] },
        { text: "Star", emoji: "⭐", accepted: ["stars"] },
        { text: "Heart", emoji: "❤️", accepted: ["love", "hearts"] },
        { text: "Oval", emoji: "🥚", accepted: ["ovals"] },
        { text: "Diamond", emoji: "💎", accepted: ["diamonds"] },
        { text: "Pentagon", emoji: "⬠", accepted: ["pentagons"] },
        { text: "Hexagon", emoji: "⬡", accepted: ["hexagons"] },
    ],
  },
  {
    category: "Types of Drinks",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Water", emoji: "💧" },
        { text: "Milk", emoji: "🥛" },
        { text: "Juice", emoji: "🧃" },
        { text: "Soda", emoji: "🥤" },
        { text: "Lemonade", emoji: "🍋" },
        { text: "Tea", emoji: "🍵" },
        { text: "Coffee", emoji: "☕" },
        { text: "Hot Chocolate", emoji: "🍫" },
        { text: "Smoothie", emoji: "🍓", accepted: ["smoothies"] },
        { text: "Milkshake", emoji: "🥤", accepted: ["milkshakes"] },
    ],
  },

  // Not-so-easy Difficulty
  {
    category: "Things You Find at the Beach",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Sand", emoji: "🏖️" },
      { text: "Water", emoji: "💧" },
      { text: "Seashells", emoji: "🐚", accepted: ["seashell"] },
      { text: "Sunscreen", emoji: "🧴" },
      { text: "Towel", emoji: "🧺", accepted: ["towels"] },
      { text: "Umbrella", emoji: "⛱️", accepted: ["umbrellas"] },
      { text: "Crab", emoji: "🦀", accepted: ["crabs"] },
      { text: "Seagull", emoji: "🐦", accepted: ["seagulls"] },
      { text: "Waves", emoji: "🌊", accepted: ["wave"] },
      { text: "Bucket", emoji: "🪣", accepted: ["buckets"] },
    ],
  },
  {
    category: "Pizza Toppings",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Pepperoni", emoji: "🍕" },
      { text: "Mushrooms", emoji: "🍄", accepted: ["mushroom"] },
      { text: "Onions", emoji: "🧅", accepted: ["onion"] },
      { text: "Sausage", emoji: "🌭" },
      { text: "Bacon", emoji: "🥓" },
      { text: "Extra Cheese", emoji: "🧀" },
      { text: "Black Olives", emoji: "🫒", accepted: ["black olive"] },
      { text: "Green Peppers", emoji: "🫑", accepted: ["green pepper"] },
      { text: "Pineapple", emoji: "🍍" },
      { text: "Spinach", emoji: "🥬" },
    ],
  },
  {
    category: "Things in a Supermarket",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Shopping Cart", emoji: "🛒", accepted: ["shopping carts"] },
      { text: "Cashier", emoji: "🧑‍💼", accepted: ["cashiers"] },
      { text: "Aisle", emoji: "🚶", accepted: ["aisles"] },
      { text: "Fruits", emoji: "🍎", accepted: ["fruit"] },
      { text: "Vegetables", emoji: "🥕", accepted: ["vegetable"] },
      { text: "Milk", emoji: "🥛" },
      { text: "Bread", emoji: "🍞" },
      { text: "Cereal", emoji: "🥣" },
      { text: "Checkout Counter", emoji: "🧾" },
      { text: "Meat", emoji: "🥩" },
    ],
  },
  {
    category: "Weekend Activities",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Watch Movies", emoji: "🎬" },
      { text: "Play Sports", emoji: "⚽" },
      { text: "Go Shopping", emoji: "🛍️" },
      { text: "Visit Friends", emoji: "🧑‍🤝‍🧑" },
      { text: "Sleep In", emoji: "😴" },
      { text: "Read a Book", emoji: "📚" },
      { text: "Play Video Games", emoji: "🎮" },
      { text: "Go to the Park", emoji: "🏞️" },
      { text: "Clean the House", emoji: "🧹" },
      { text: "Eat Out", emoji: "🍔" },
    ],
  },
  {
    category: "Types of Weather",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Sunny", emoji: "☀️" },
      { text: "Rainy", emoji: "🌧️" },
      { text: "Cloudy", emoji: "☁️" },
      { text: "Snowy", emoji: "❄️" },
      { text: "Windy", emoji: "💨" },
      { text: "Stormy", emoji: "⛈️" },
      { text: "Foggy", emoji: "🌫️" },
      { text: "Hailing", emoji: "🌨️" },
      { text: "Hot", emoji: "🔥" },
      { text: "Cold", emoji: "🥶" },
    ],
  },
  {
    category: "Things in a Kitchen",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Stove", emoji: "🔥", accepted: ["stoves"] },
        { text: "Refrigerator", emoji: "🧊", accepted: ["fridge", "fridges"] },
        { text: "Sink", emoji: "💧", accepted: ["sinks"] },
        { text: "Microwave", emoji: "⚡", accepted: ["microwaves"] },
        { text: "Oven", emoji: "🍞", accepted: ["ovens"] },
        { text: "Toaster", emoji: "🍞", accepted: ["toasters"] },
        { text: "Blender", emoji: "🍹", accepted: ["blenders"] },
        { text: "Plate", emoji: "🍽️", accepted: ["plates"] },
        { text: "Fork", emoji: "🍴", accepted: ["forks"] },
        { text: "Spoon", emoji: "🥄", accepted: ["spoons"] },
    ],
  },
  {
    category: "Things That Are Round",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Ball", emoji: "🏀", accepted: ["balls"] },
        { text: "Orange", emoji: "🍊", accepted: ["oranges"] },
        { text: "Wheel", emoji: "☸️", accepted: ["wheels"] },
        { text: "Pizza", emoji: "🍕", accepted: ["pizzas"] },
        { text: "Coin", emoji: "🪙", accepted: ["coins"] },
        { text: "Button", emoji: "🔘", accepted: ["buttons"] },
        { text: "Earth", emoji: "🌍" },
        { text: "Sun", emoji: "☀️" },
        { text: "Clock", emoji: "⏰", accepted: ["clocks"] },
        { text: "Donut", emoji: "🍩", accepted: ["donuts"] },
    ],
  },
  {
    category: "Ice Cream Flavors",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Vanilla", emoji: "🍦" },
        { text: "Chocolate", emoji: "🍫" },
        { text: "Strawberry", emoji: "🍓" },
        { text: "Mint Chocolate Chip", emoji: "🍃" },
        { text: "Cookie Dough", emoji: "🍪" },
        { text: "Rocky Road", emoji: "🍫" },
        { text: "Butter Pecan", emoji: "🥜" },
        { text: "Cookies and Cream", emoji: "🍪" },
        { text: "Neapolitan", emoji: "🍦" },
        { text: "Pistachio", emoji: "🟢" },
    ],
  },
  {
    category: "Things You Do at a Party",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Eat Cake", emoji: "🎂" },
        { text: "Dance", emoji: "💃" },
        { text: "Sing", emoji: "🎤" },
        { text: "Play Games", emoji: "🎲" },
        { text: "Talk to Friends", emoji: "💬" },
        { text: "Open Presents", emoji: "🎁" },
        { text: "Blow out Candles", emoji: "🕯️" },
        { text: "Listen to Music", emoji: "🎶" },
        { text: "Laugh", emoji: "😄" },
        { text: "Drink Punch", emoji: "🥤" },
    ],
  },
  {
    category: "Ocean Animals",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Fish", emoji: "🐠", accepted: ["fishes"] },
        { text: "Whale", emoji: "🐋", accepted: ["whales"] },
        { text: "Dolphin", emoji: "🐬", accepted: ["dolphins"] },
        { text: "Shark", emoji: "🦈", accepted: ["sharks"] },
        { text: "Octopus", emoji: "🐙", accepted: ["octopuses", "octopi"] },
        { text: "Jellyfish", emoji: "🪼", accepted: ["jellyfishes"] },
        { text: "Sea Turtle", emoji: "🐢", accepted: ["sea turtles"] },
        { text: "Starfish", emoji: "⭐", accepted: ["starfishes"] },
        { text: "Crab", emoji: "🦀", accepted: ["crabs"] },
        { text: "Seahorse", emoji: "🐠", accepted: ["seahorses"] },
    ],
  },

  // Hard Difficulty
  {
    category: "U.S. State Capitals",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Sacramento", emoji: "🐻" },
      { text: "Austin", emoji: "⭐" },
      { text: "Tallahassee", emoji: "☀️" },
      { text: "Albany", emoji: "🏛️" },
      { text: "Columbus", emoji: "🌰" },
      { text: "Boston", emoji: "🍵" },
      { text: "Atlanta", emoji: "🍑" },
      { text: "Denver", emoji: "🏔️" },
      { text: "Phoenix", emoji: "🌵" },
      { text: "Harrisburg", emoji: "🔔" },
    ],
  },
  {
    category: "Famous Scientists",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Albert Einstein", emoji: "🔬" },
      { text: "Isaac Newton", emoji: "🍎" },
      { text: "Marie Curie", emoji: "☢️" },
      { text: "Galileo Galilei", emoji: "🔭" },
      { text: "Charles Darwin", emoji: "🐒" },
      { text: "Nikola Tesla", emoji: "💡" },
      { text: "Stephen Hawking", emoji: "🌌" },
      { text: "Louis Pasteur", emoji: "🥛" },
      { text: "Thomas Edison", emoji: "💡" },
      { text: "Rosalind Franklin", emoji: "🧬" },
    ],
  },
  {
    category: "Parts of a Car",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Engine", emoji: "⚙️", accepted: ["engines"] },
      { text: "Wheel", emoji: "🔘", accepted: ["wheels"] },
      { text: "Steering Wheel", emoji: "☸️" },
      { text: "Brake", emoji: "🛑", accepted: ["brakes"] },
      { text: "Seat", emoji: "💺", accepted: ["seats"] },
      { text: "Door", emoji: "🚪", accepted: ["doors"] },
      { text: "Window", emoji: "🖼️", accepted: ["windows"] },
      { text: "Headlight", emoji: "💡", accepted: ["headlights"] },
      { text: "Tire", emoji: "🔘", accepted: ["tires"] },
      { text: "Exhaust Pipe", emoji: "💨" },
    ],
  },
  {
    category: "Countries in South America",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Brazil", emoji: "🇧🇷" },
      { text: "Argentina", emoji: "🇦🇷" },
      { text: "Colombia", emoji: "🇨🇴" },
      { text: "Peru", emoji: "🇵🇪" },
      { text: "Chile", emoji: "🇨🇱" },
      { text: "Venezuela", emoji: "🇻🇪" },
      { text: "Ecuador", emoji: "🇪🇨" },
      { text: "Bolivia", emoji: "🇧🇴" },
      { text: "Uruguay", emoji: "🇺🇾" },
      { text: "Paraguay", emoji: "🇵🇾" },
    ],
  },
  {
    category: "Musical Instruments in an Orchestra",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Violin", emoji: "🎻", accepted: ["violins"] },
      { text: "Cello", emoji: "🎻", accepted: ["cellos"] },
      { text: "Trumpet", emoji: "🎺", accepted: ["trumpets"] },
      { text: "Flute", emoji: "🎶", accepted: ["flutes"] },
      { text: "Clarinet", emoji: "🎶", accepted: ["clarinets"] },
      { text: "Trombone", emoji: "🎺", accepted: ["trombones"] },
      { text: "Tuba", emoji: "🎺", accepted: ["tubas"] },
      { text: "Drums", emoji: "🥁", accepted: ["drum"] },
      { text: "Piano", emoji: "🎹", accepted: ["pianos"] },
      { text: "Harp", emoji: "🎼", accepted: ["harps"] },
    ],
  },
  {
    category: "Things in a Toolbox",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Hammer", emoji: "🔨", accepted: ["hammers"] },
      { text: "Screwdriver", emoji: "🔩", accepted: ["screwdrivers"] },
      { text: "Wrench", emoji: "🔧", accepted: ["wrenches"] },
      { text: "Pliers", emoji: "🛠️" },
      { text: "Tape Measure", emoji: "📏" },
      { text: "Drill", emoji: "🔩", accepted: ["drills"] },
      { text: "Saw", emoji: "🪚", accepted: ["saws"] },
      { text: "Nails", emoji: "🔩", accepted: ["nail"] },
      { text: "Screws", emoji: "🔩", accepted: ["screw"] },
      { text: "Level", emoji: "📏", accepted: ["levels"] },
    ],
  },
  {
    category: "Famous Landmarks",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Eiffel Tower", emoji: "🗼" },
      { text: "Statue of Liberty", emoji: "🗽" },
      { text: "Great Wall of China", emoji: "🧱" },
      { text: "Colosseum", emoji: "🏛️" },
      { text: "Pyramids of Giza", emoji: "🔺", accepted: ["pyramid of giza"] },
      { text: "Taj Mahal", emoji: "🕌" },
      { text: "Machu Picchu", emoji: "🏞️" },
      { text: "Big Ben", emoji: "🕰️" },
      { text: "Sydney Opera House", emoji: "🎭" },
      { text: "Mount Rushmore", emoji: "⛰️" },
    ],
  },
  {
    category: "Planets in Our Solar System",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Mercury", emoji: "🪐" },
      { text: "Venus", emoji: "🪐" },
      { text: "Earth", emoji: "🌍" },
      { text: "Mars", emoji: "🪐" },
      { text: "Jupiter", emoji: "🪐" },
      { text: "Saturn", emoji: "🪐" },
      { text: "Uranus", emoji: "🪐" },
      { text: "Neptune", emoji: "🪐" },
      { text: "Pluto", emoji: "🪐", accepted: ["dwarf planet"] },
      { text: "Sun", emoji: "☀️", accepted: ["star"] },
    ],
  },
  {
    category: "Jobs in a Hospital",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Doctor", emoji: "👨‍⚕️" },
      { text: "Nurse", emoji: "👩‍⚕️" },
      { text: "Surgeon", emoji: "⚕️" },
      { text: "Paramedic", emoji: "🚑" },
      { text: "Receptionist", emoji: "📠" },
      { text: "Pharmacist", emoji: "💊" },
      { text: "Radiologist", emoji: "☢️" },
      { text: "Anesthesiologist", emoji: "😴" },
      { text: "Janitor", emoji: "🧹" },
      { text: "Therapist", emoji: "🛋️" },
    ],
  },
  {
    category: "Types of Dinosaurs",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Tyrannosaurus Rex", emoji: "🦖", accepted: ["t-rex"] },
      { text: "Triceratops", emoji: "🦖" },
      { text: "Stegosaurus", emoji: "🦖" },
      { text: "Velociraptor", emoji: "🦅", accepted: ["raptor"] },
      { text: "Brachiosaurus", emoji: "🦕" },
      { text: "Pterodactyl", emoji: "🦅" },
      { text: "Ankylosaurus", emoji: "🛡️" },
      { text: "Spinosaurus", emoji: "🦖" },
      { text: "Diplodocus", emoji: "🦕" },
      { text: "Allosaurus", emoji: "🦖" },
    ],
  },

  // DEATH MODE Difficulty
  {
    category: "Types of Logical Fallacies",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Ad Hominem", emoji: "🗣️" },
      { text: "Straw Man", emoji: "🌾" },
      { text: "Slippery Slope", emoji: "📉" },
      { text: "False Dichotomy", emoji: "🌓" },
      { text: "Red Herring", emoji: "🐟" },
      { text: "Appeal to Authority", emoji: "👑" },
      { text: "Circular Reasoning", emoji: "🔄" },
      { text: "Bandwagon", emoji: "🎉" },
      { text: "Hasty Generalization", emoji: "🏃" },
      { text: "Post Hoc Ergo Propter Hoc", emoji: "🐔" },
    ],
  },
  {
    category: "Characters from Shakespearean Tragedies",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Hamlet", emoji: "💀" },
      { text: "Macbeth", emoji: "👑" },
      { text: "King Lear", emoji: "👑" },
      { text: "Othello", emoji: "🎭" },
      { text: "Romeo", emoji: "❤️" },
      { text: "Juliet", emoji: "❤️" },
      { text: "Titus Andronicus", emoji: "🏛️" },
      { text: "Brutus", emoji: "🗡️" },
      { text: "Ophelia", emoji: "🌸" },
      { text: "Desdemona", emoji: "🤧" },
    ],
  },
  {
    category: "Elements on the Periodic Table (Not in the First 20)",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Iron (Fe)", emoji: "🔩" },
      { text: "Gold (Au)", emoji: "🥇" },
      { text: "Silver (Ag)", emoji: "🥈" },
      { text: "Lead (Pb)", emoji: "⛓️" },
      { text: "Uranium (U)", emoji: "⚛️" },
      { text: "Mercury (Hg)", emoji: "🌡️" },
      { text: "Copper (Cu)", emoji: "🥉" },
      { text: "Tin (Sn)", emoji: "🥫" },
      { text: "Zinc (Zn)", emoji: "🧪" },
      { text: "Platinum (Pt)", emoji: "💎" },
    ],
  },
  {
    category: "Bones in the Human Hand and Wrist",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Phalanges", emoji: "🖐️", accepted: ["phalanx"] },
      { text: "Metacarpals", emoji: "🖐️", accepted: ["metacarpal"] },
      { text: "Carpals", emoji: "🖐️", accepted: ["carpal"] },
      { text: "Scaphoid", emoji: "🦴" },
      { text: "Lunate", emoji: "🦴" },
      { text: "Triquetrum", emoji: "🦴" },
      { text: "Pisiform", emoji: "🦴" },
      { text: "Trapezium", emoji: "🦴" },
      { text: "Trapezoid", emoji: "🦴" },
      { text: "Capitate", emoji: "🦴" },
    ],
  },
  {
    category: "Programming Languages Created Before 1980",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Fortran", emoji: "🔢" },
      { text: "Lisp", emoji: "🧠" },
      { text: "COBOL", emoji: "💼" },
      { text: "ALGOL", emoji: "📐" },
      { text: "BASIC", emoji: "🏫" },
      { text: "Pascal", emoji: "👨‍🏫" },
      { text: "C", emoji: "🥉" },
      { text: "Simula", emoji: "💻" },
      { text: "APL", emoji: "📈" },
      { text: "PL/I", emoji: "💻" },
    ],
  },
  {
    category: "Nobel Prize Winners in Physics",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Marie Curie", emoji: "☢️" },
      { text: "Albert Einstein", emoji: "🔬" },
      { text: "Max Planck", emoji: "💡" },
      { text: "Niels Bohr", emoji: "⚛️" },
      { text: "Werner Heisenberg", emoji: "🤔" },
      { text: "Erwin Schrödinger", emoji: "🐈" },
      { text: "Richard Feynman", emoji: "📈" },
      { text: "Enrico Fermi", emoji: "⚛️" },
      { text: "Paul Dirac", emoji: "⚛️" },
      { text: "Hideki Yukawa", emoji: "⚛️" },
    ],
  },
  {
    category: "Ancient Greek Philosophers",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Socrates", emoji: "🤔" },
      { text: "Plato", emoji: "📖" },
      { text: "Aristotle", emoji: "👨‍🏫" },
      { text: "Pythagoras", emoji: "📐" },
      { text: "Heraclitus", emoji: "🔥" },
      { text: "Democritus", emoji: "⚛️" },
      { text: "Diogenes", emoji: "🐕" },
      { text: "Epicurus", emoji: "😊" },
      { text: "Zeno of Citium", emoji: "🏛️" },
      { text: "Thales of Miletus", emoji: "🌊" },
    ],
  },
  {
    category: "Mythical Creatures",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Dragon", emoji: "🐉" },
      { text: "Unicorn", emoji: "🦄" },
      { text: "Griffin", emoji: "🦅" },
      { text: "Phoenix", emoji: "🔥" },
      { text: "Centaur", emoji: "🐴" },
      { text: "Minotaur", emoji: "🐂" },
      { text: "Hydra", emoji: "🐍" },
      { text: "Kraken", emoji: "🐙" },
      { text: "Sphinx", emoji: "🦁" },
      { text: "Medusa", emoji: "🐍" },
    ],
  },
  {
    category: "Terms from Chess",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Checkmate", emoji: "♚" },
      { text: "Stalemate", emoji: "🤝" },
      { text: "Castling", emoji: "🏰" },
      { text: "En Passant", emoji: "♟️" },
      { text: "Pawn", emoji: "♙" },
      { text: "Rook", emoji: "♖" },
      { text: "Knight", emoji: "♘" },
      { text: "Bishop", emoji: "♗" },
      { text: "Queen", emoji: "♕" },
      { text: "King", emoji: "♔" },
    ],
  },
  {
    category: "Composers of the Baroque Period",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Johann Sebastian Bach", emoji: "🎼" },
      { text: "George Frideric Handel", emoji: "🎼" },
      { text: "Antonio Vivaldi", emoji: "🎻" },
      { text: "Claudio Monteverdi", emoji: "🎼" },
      { text: "Henry Purcell", emoji: "🎼" },
      { text: "Domenico Scarlatti", emoji: "🎹" },
      { text: "Arcangelo Corelli", emoji: "🎻" },
      { text: "Jean-Philippe Rameau", emoji: "🎼" },
      { text: "Georg Philipp Telemann", emoji: "🎼" },
      { text: "Johann Pachelbel", emoji: "🎼" },
    ],
  },
];