
import { Difficulty, GameData } from './types';

export const gameData: GameData[] = [
  // Easy Difficulty
  {
    category: "Colors of the Rainbow",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Red", emoji: "🔴" },
      { text: "Orange", emoji: "🟠" },
      { text: "Yellow", emoji: "🟡" },
      { text: "Green", emoji: "🟢" },
      { text: "Blue", emoji: "🔵" },
      { text: "Indigo", emoji: "🟣" },
      { text: "Violet", emoji: "💜" },
      { text: "Purple", emoji: "🍇" },
      { text: "Pink", emoji: "🌸" },
      { text: "Brown", emoji: "🟤" },
    ],
  },
  {
    category: "Things in a Classroom",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Desk", emoji: "🗃", accepted: ["table"] },
      { text: "Chair", emoji: "🪑", accepted: ["chairs"] },
      { text: "Board", emoji: "📋", accepted: ["blackboard", "whiteboard", "chalkboard"] },
      { text: "Pens", emoji: "✍️", accepted: ["pen"] },
      { text: "Book", emoji: "📖", accepted: ["books"] },
      { text: "Pencil", emoji: "✏️", accepted: ["pencils"] },
      { text: "Teacher", emoji: "🧑‍🏫", accepted: ["teachers"] },
      { text: "Student", emoji: "🧑‍🎓", accepted: ["students"] },
      { text: "Chalks", emoji: "📝", accepted: ["chalk"]  },
      { text: "Computer", emoji: "💻", accepted: ["computers"] },
    ],
  },
  {
    category: "Types of Fruit",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Apple", emoji: "🍎", accepted: ["apples"] },
      { text: "Banana", emoji: "🍌", accepted: ["bananas"] },
      { text: "Orange", emoji: "🍊", accepted: ["oranges"] },
      { text: "Grapes", emoji: "🍇", accepted: ["grape"] },
      { text: "Strawberry", emoji: "🍓", accepted: ["strawberries"] },
      { text: "Watermelon", emoji: "🍉", accepted: ["watermelons"] },
      { text: "Pineapple", emoji: "🍍", accepted: ["pineapples"] },
      { text: "Mango", emoji: "🥭", accepted: ["mangos", "mangoes"] },
      { text: "Blueberry", emoji: "🫐", accepted: ["blueberries"] },
      { text: "Peach", emoji: "🍑", accepted: ["peaches"] },
    ],
  },
  {
    category: "Farm Animals",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Cow", emoji: "🐮", accepted: ["cows"] },
      { text: "Pig", emoji: "🐷", accepted: ["pigs"] },
      { text: "Chicken", emoji: "🐔", accepted: ["chickens", "chick"] },
      { text: "Horse", emoji: "🐴", accepted: ["horses", "pony"] },
      { text: "Sheep", emoji: "🐑" },
      { text: "Goat", emoji: "🐐", accepted: ["goats"] },
      { text: "Duck", emoji: "🦆", accepted: ["ducks"] },
      { text: "Dog", emoji: "🐶", accepted: ["dogs"] },
      { text: "Cat", emoji: "🐱", accepted: ["cats"] },
      { text: "Donkey", emoji: "🫏", accepted: ["donkeys"] },
    ],
  },
  {
    category: "Things You Wear",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Shirt", emoji: "👕", accepted: ["t-shirt", "tshirt", "teeshirt", "shirts"] },
      { text: "Pants", emoji: "👖" },
      { text: "Shoes", emoji: "👟", accepted: ["shoe"] },
      { text: "Socks", emoji: "🧦", accepted: ["sock"] },
      { text: "Hat", emoji: "🧢", accepted: ["hats"] },
      { text: "Jacket", emoji: "🧥", accepted: ["jackets"] },
      { text: "Dress", emoji: "👗", accepted: ["dresses"] },
      { text: "Skirt", emoji: "🎽", accepted: ["skirts"] },
      { text: "Gloves", emoji: "🧤", accepted: ["glove"] },
      { text: "Scarf", emoji: "🧣", accepted: ["scarves"] },
    ],
  },
  {
    category: "Breakfast Foods",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Cereal", emoji: "🥣" },
      { text: "Eggs", emoji: "🍳", accepted: ["egg"] },
      { text: "Hamburgers", emoji: "🥞", accepted: ["hamburger", "burger"] },
      { text: "Bacon", emoji: "🥓" },
      { text: "Toast", emoji: "🍞", accepted: ["bread", "sandwich"] },
      { text: "Sausage", emoji: "🌭", accepted: ["sausages", "hotdog", "ham"] },
      { text: "Waffles", emoji: "🧇", accepted: ["waffle"] },
      { text: "Oatmeal", emoji: "🥣" },
      { text: "Pancakes", emoji: "🧇", accepted: ["pancake"] },
      { text: "Milk", emoji: "🥛" },
    ],
  },
  {
    category: "Zoo Animals",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Lion", emoji: "🦁", accepted: ["lions"] },
        { text: "Tiger", emoji: "🐯", accepted: ["tigers"] },
        { text: "Elephant", emoji: "🐘", accepted: ["elephants"] },
        { text: "Monkey", emoji: "🐵", accepted: ["monkeys"] },
        { text: "Giraffe", emoji: "🦒", accepted: ["giraffes"] },
        { text: "Zebra", emoji: "🦓", accepted: ["zebras"] },
        { text: "Bear", emoji: "🐻", accepted: ["bears"] },
        { text: "Penguin", emoji: "🐧", accepted: ["penguins"] },
        { text: "Kangaroo", emoji: "🦘", accepted: ["kangaroos"] },
        { text: "Hippo", emoji: "🦛", accepted: ["hippos", "hippopotamus"] },
    ],
  },
  {
    category: "Things in the Sky",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Sun", emoji: "☀️" },
        { text: "Moon", emoji: "🌙" },
        { text: "Stars", emoji: "⭐", accepted: ["star"] },
        { text: "Clouds", emoji: "☁️", accepted: ["cloud"] },
        { text: "Airplane", emoji: "✈️", accepted: ["airplanes", "plane", "planes", "jet"] },
        { text: "Bird", emoji: "🐦", accepted: ["birds", "eagle"] },
        { text: "Kite", emoji: "🪁", accepted: ["kites"] },
        { text: "Rainbow", emoji: "🌈", accepted: ["rainbows"] },
        { text: "Helicopter", emoji: "🚁", accepted: ["helicopters"] },
        { text: "Rocket", emoji: "🚀", accepted: ["rockets"] },
    ],
  },
  {
    category: "Shapes",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Circle", emoji: "⭕", accepted: ["round", "circles"] },
        { text: "Square", emoji: "⬜", accepted: ["squares"] },
        { text: "Triangle", emoji: "🔼", accepted: ["triangles"] },
        { text: "Rectangle", emoji: "▭", accepted: ["rectangles"] },
        { text: "Star", emoji: "⭐", accepted: ["stars"] },
        { text: "Heart", emoji: "❤️", accepted: ["love", "hearts"] },
        { text: "Oval", emoji: "🥚", accepted: ["ovals"] },
        { text: "Diamond", emoji: "💎", accepted: ["diamonds"] },
        { text: "Pentagon", emoji: "⬠", accepted: ["pentagons"] },
        { text: "Hexagon", emoji: "⬡", accepted: ["hexagons"] },
    ],
  },
  {
    category: "Types of Drinks",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Water", emoji: "💧" },
        { text: "Milk", emoji: "🥛", accepted: ["chocolate milk", "strawberry milk"] },
        { text: "Juice", emoji: "🧃" },
        { text: "Soda", emoji: "🥤", accepted: ["cola", "Coca Cola", "Fanta", "coke"] },
        { text: "Lemonade", emoji: "🍋" },
        { text: "Tea", emoji: "🍵", accepted: ["milk tea", "bubble tea", "bubble milk tea"]},
        { text: "Coffee", emoji: "☕", accepted: ["latte", "cappuccino"] },
        { text: "Hot Chocolate", emoji: "🍫", accepted: ["chocolate"] },
        { text: "Smoothie", emoji: "🍓", accepted: ["smoothies"] },
        { text: "Milkshake", emoji: "🥤", accepted: ["milkshakes"] },
    ],
  },
  {
    category: "Common Household Pets",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Dog", emoji: "🐶" },
      { text: "Cat", emoji: "🐱" },
      { text: "Fish", emoji: "🐠", accepted: ["goldfish"] },
      { text: "Hamster", emoji: "🐹" },
      { text: "Parrot", emoji: "🦜", accepted: ["bird"]  },
      { text: "Rabbit", emoji: "🐰" },
      { text: "Guinea Pig", emoji: "🐹" },
      { text: "Turtle", emoji: "🐢" },
      { text: "Snake", emoji: "🐍" },
      { text: "Mouse", emoji: "🐭" },
    ],
  },
  {
    category: "Seasons",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Spring", emoji: "🌸" },
      { text: "Summer", emoji: "☀️" },
      { text: "Autumn", emoji: "🍂", accepted: ["fall"] },
      { text: "Winter", emoji: "❄️" },
      { text: "Rainy Season", emoji: "🌧️", accepted: ["rain", "rainy"]  },
      { text: "Dry Season", emoji: "🌵", accepted: ["dry"] },
      { text: "Monsoon", emoji: " monsoon " },
      { text: "Harvest", emoji: "🌾" },
      { text: "Planting", emoji: "🌱" },
      { text: "Growing Season", emoji: "📈" },
    ],
  },
  {
    category: "Days of the Week",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Monday", emoji: " M " },
      { text: "Tuesday", emoji: " T " },
      { text: "Wednesday", emoji: " W " },
      { text: "Thursday", emoji: " Th " },
      { text: "Friday", emoji: " F " },
      { text: "Saturday", emoji: " Sa " },
      { text: "Sunday", emoji: " Su " },
      { text: "Weekend", emoji: "🎉" },
      { text: "Weekday", emoji: "💼" },
      { text: "Tomorrow", emoji: "➡️" },
    ],
  },
  {
    category: "Jobs People Do",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Doctor", emoji: "🧑‍⚕️", accepted: ["nurse"] },
      { text: "Teacher", emoji: "🧑‍🏫" },
      { text: "Firefighter", emoji: "👨‍🚒", accepted: ["fireman"] },
      { text: "Police Officer", emoji: "👮", accepted: ["police", "policeman"] },
      { text: "Farmer", emoji: "🧑‍🌾" },
      { text: "Cook", emoji: "🧑‍🍳", accepted: ["chef"] },
      { text: "Pilot", emoji: "👨‍✈️" },
      { text: "Singer", emoji: "🧑‍🎤" },
      { text: "Artist", emoji: "🧑‍🎨", accepted: ["painter"] },
      { text: "Driver", emoji: "🧑‍✈️", accepted: ["bus driver", "taxi driver"] },
    ],
  },
  {
    category: "Things That Go",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Car", emoji: "🚗", accepted: ["cars"] },
      { text: "Bus", emoji: "🚌", accepted: ["buses"] },
      { text: "Train", emoji: "🚂", accepted: ["trains"] },
      { text: "Airplane", emoji: "✈️", accepted: ["plane", "planes"] },
      { text: "Boat", emoji: "⛵️", accepted: ["ship"] },
      { text: "Bicycle", emoji: "🚲", accepted: ["bike"] },
      { text: "Truck", emoji: "🚚" },
      { text: "Motorcycle", emoji: "🏍️" },
      { text: "Rocket", emoji: "🚀" },
      { text: "Helicopter", emoji: "🚁" },
    ],
  },
  {
    category: "Parts of Your Body",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Eyes", emoji: "👀", accepted: ["eye"] },
      { text: "Nose", emoji: "👃" },
      { text: "Mouth", emoji: "👄" },
      { text: "Ears", emoji: "👂", accepted: ["ear"] },
      { text: "Hands", emoji: "✋", accepted: ["hand"] },
      { text: "Feet", emoji: "🦶", accepted: ["foot"] },
      { text: "Hair", emoji: "👱" },
      { text: "Head", emoji: "👨" },
      { text: "Legs", emoji: "🦵", accepted: ["leg"] },
      { text: "Arms", emoji: "💪", accepted: ["arm"] },
    ],
  },
  {
    category: "Things You Find in a Park",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Slide", emoji: "🛝" },
      { text: "Swing", emoji: "🪱" },
      { text: "Bench", emoji: "🪑" },
      { text: "Tree", emoji: "🌳", accepted: ["trees"] },
      { text: "Grass", emoji: "🌿" },
      { text: "Ball", emoji: "⚽" },
      { text: "Flowers", emoji: "🌸", accepted: ["flower"] },
      { text: "Fountain", emoji: "⛲" },
      { text: "Dog", emoji: "🐕", accepted: ["dogs"] },
      { text: "People", emoji: "👨‍👩‍👧‍👦", accepted: ["person", "kids", "children"] },
    ],
  },
  {
    category: "Things That Are Sweet",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Candy", emoji: "🍬", accepted: ["candies", "sweets"] },
      { text: "Cake", emoji: "🍰" },
      { text: "Ice Cream", emoji: "🍦" },
      { text: "Chocolate", emoji: "🍫" },
      { text: "Honey", emoji: "🍯" },
      { text: "Sugar", emoji: "🍚" },
      { text: "Fruit", emoji: "🍓", accepted: ["fruits"] },
      { text: "Cookies", emoji: "🍪", accepted: ["cookie"] },
      { text: "Donuts", emoji: "🍩", accepted: ["donut"] },
      { text: "Soda", emoji: "🥤", accepted: ["coke", "pop"] },
    ],
  },
  {
    category: "Animal Sounds",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Moo", emoji: "🐮" },
      { text: "Oink", emoji: "🐷" },
      { text: "Bark", emoji: "🐶", accepted: ["woof"] },
      { text: "Meow", emoji: "🐱" },
      { text: "Quack", emoji: "🦆" },
      { text: "Roar", emoji: "🦁" },
      { text: "Tweet", emoji: "🐦", accepted: ["chirp"] },
      { text: "Neigh", emoji: "🐴" },
      { text: "Baa", emoji: "🐑" },
      { text: "Hiss", emoji: "🐍" },
    ],
  },
  {
    category: "Places to Go",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "School", emoji: "🏫" },
      { text: "Park", emoji: "🏞️" },
      { text: "Store", emoji: "🏪", accepted: ["supermarket", "shop"] },
      { text: "Zoo", emoji: "🦓" },
      { text: "Beach", emoji: "🏖️" },
      { text: "Library", emoji: "📚" },
      { text: "Museum", emoji: "🏛️" },
      { text: "Restaurant", emoji: "🍔", accepted: ["cafe"] },
      { text: "Home", emoji: "🏠", accepted: ["house"] },
      { text: "Hospital", emoji: "🏥", accepted: ["doctor"] },
    ],
  },

  // Not-so-easy Difficulty
  {
    category: "Taiwanese Night Market Snacks",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Stinky Tofu", emoji: "🧆", accepted: ["chou dou fu"] },
      { text: "Bubble Tea", emoji: "🧋", accepted: ["boba", "pearl milk tea", "zhen zhu nai cha", "milk tea", "bubble milk tea"] },
      { text: "Oyster Omelet", emoji: "🍳", accepted: ["e-a-jian", "oyster pancake", "oyster omelette", "e a jian"] },
      { text: "Fried Chicken Fillet", emoji: "🍗", accepted: ["large fried chicken", "ji pai"] },
      { text: "Sweet Potato Balls", emoji: "🍠", accepted: ["di gua qiu"] },
      { text: "Grilled Corn", emoji: "🌽", accepted: ["kao yu mi", "corn"] },
      { text: "Braised Pork Rice", emoji: "🍚", accepted: ["lu rou fan"] },
      { text: "Mango Shaved Ice", emoji: "🍧", accepted: ["mango ice", "mang guo bing"] },
      { text: "Pepper Bun", emoji: "🥯", accepted: ["hu jiao bing"] },
      { text: "Papaya Milk", emoji: "🥛", accepted: ["mu gua niu nai", "xi gua niu nai", "watermelon milk"] },
    ],
  },
  {
    category: "Things in a Taiwanese Convenience Store",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Tea Eggs", emoji: "🥚", accepted: ["cha ye dan", "tea boiled egg", "tea egg", "tea boiled eggs"] },
      { text: "Onigiri", emoji: "🍙", accepted: ["rice ball"] },
      { text: "Coffee", emoji: "☕", accepted: ["city cafe", "latte", "americano"] },
      { text: "Microwave Meals", emoji: "🍱", accepted: ["lunch box", "bentos", "bento"] },
      { text: "Drinks", emoji: "🧃", accepted: ["bottled water", "tea", "soda"] },
      { text: "Snacks", emoji: "🥨", accepted: ["chips", "cookies", "candy"] },
      { text: "Parcel Pickup", emoji: "📦", accepted: ["packages", "delivery"] },
      { text: "ATM", emoji: "🏦", accepted: ["bank machine", "cash", "money machine"] },
      { text: "Printing Service", emoji: "🖨️", accepted: ["copy machine", "scanning", "ibon"] },
      { text: "EasyCard Top-up", emoji: "💳", accepted: ["yo-yo card", "adding money"] },
    ],
  },
  {
    category: "Taiwanese Breakfast Favorites",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Egg Pancake", emoji: "🥞", accepted: ["dan bing"] },
      { text: "Soy Milk", emoji: "🥛", accepted: ["dou jiang"] },
      { text: "Radish Cake", emoji: "🍰", accepted: ["luo bo gao", "turnip cake"] },
      { text: "Rice Ball", emoji: "🍙", accepted: ["fan tuan"] },
      { text: "Sandwich", emoji: "🥪", accepted: ["breakfast sandwich"] },
      { text: "Hamburger", emoji: "🍔", accepted: ["breakfast burger"] },
      { text: "You Tiao", emoji: "🥖", accepted: ["fried dough stick"] },
      { text: "Milk Tea", emoji: "🧋", accepted: ["breakfast milk tea"] },
      { text: "Hash Browns", emoji: "🥔", accepted: ["shu bing"] },
      { text: "Iron Plate Noodles", emoji: "🍝", accepted: ["tie ban mian"] },
    ],
  },
  {
    category: "Bubble Tea Shop Orders",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Pearl Milk Tea", emoji: "🧋", accepted: ["boba milk tea", "zhen zhu nai cha", "bubble milk tea"] },
      { text: "Fruit Tea", emoji: "🍎", accepted: ["shui guo cha"] },
      { text: "Black Tea", emoji: "☕", accepted: ["hong cha"] },
      { text: "Green Tea", emoji: "🍵", accepted: ["lv cha"] },
      { text: "Oolong Tea", emoji: "🍂", accepted: ["wu long cha"] },
      { text: "Winter Melon Tea", emoji: "🍈", accepted: ["dong gua cha"] },
      { text: "Taro Milk", emoji: "🍠", accepted: ["yu tou nai cha"] },
      { text: "Matcha Latte", emoji: "🌿", accepted: ["matcha milk"] },
      { text: "Lemon Green Tea", emoji: "🍋", accepted: ["ning meng lv cha"] },
      { text: "Milk Foam Tea", emoji: "☁️", accepted: ["cheese foam", "nai gai"] },
    ],
  },
  {
    category: "Transportation in Taiwan",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Scooter", emoji: "🛵", accepted: ["motorcycle", "ji che"] },
      { text: "MRT", emoji: "🚇", accepted: ["subway", "metro", "jie yun"] },
      { text: "Yellow Taxi", emoji: "🚕", accepted: ["taxi", "uber"] },
      { text: "Bus", emoji: "🚌", accepted: ["gong che"] },
      { text: "HSR", emoji: "🚄", accepted: ["high speed rail", "gao tie"] },
      { text: "TRA Train", emoji: "🚃", accepted: ["train", "huo che", "tai tie"] },
      { text: "Ubike", emoji: "🚲", accepted: ["bicycle", "bike rental"] },
      { text: "Walking", emoji: "🚶", accepted: ["on foot"] },
      { text: "Ferry", emoji: "⛴️", accepted: ["boat", "lun chuan"] },
      { text: "Truck", emoji: "🚚", accepted: ["garbage truck"] },
    ],
  },
  {
    category: "Cities and Counties in Taiwan",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Taipei", emoji: "🏙️", accepted: ["new taipei city", "taipei city"] },
      { text: "Kaohsiung", emoji: "⚓", accepted: ["gao xiong"] },
      { text: "Taichung", emoji: "☀️", accepted: ["tai zhong"] },
      { text: "Tainan", emoji: "🏯", accepted: ["tai nan"] },
      { text: "Hsinchu", emoji: "💨", accepted: ["windy city", "xin zhu"] },
      { text: "Taoyuan", emoji: "✈️", accepted: ["tao yuan"] },
      { text: "Hualien", emoji: "⛰️", accepted: ["hua lian", "taroko"] },
      { text: "Yilan", emoji: "🌾", accepted: ["yi lan"] },
      { text: "Nantou", emoji: "🍵", accepted: ["sun moon lake", "nan tou"] },
      { text: "Taitung", emoji: "🎈", accepted: ["tai dong"] },
    ],
  },
  {
    category: "Traditional Festivals in Taiwan",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Lunar New Year", emoji: "🧧", accepted: ["chinese new year", "chun jie"] },
      { text: "Moon Festival", emoji: "🥮", accepted: ["mid-autumn festival", "zhong qiu jie"] },
      { text: "Dragon Boat Festival", emoji: "🛶", accepted: ["duan wu jie"] },
      { text: "Lantern Festival", emoji: "🏮", accepted: ["yuan xiao jie"] },
      { text: "Qingming Festival", emoji: "🕯️", accepted: ["tomb sweeping day"] },
      { text: "Ghost Festival", emoji: "👻", accepted: ["hungry ghost festival", "zhong yuan jie"] },
      { text: "Double Tenth Day", emoji: "🇹🇼", accepted: ["national day"] },
      { text: "Teacher's Day", emoji: "🧑‍🏫", accepted: ["confucius birthday"] },
      { text: "Children's Day", emoji: "🧒", accepted: ["ertong jie"] },
      { text: "Father's Day", emoji: "👔", accepted: ["ba ba jie", "august 8th"] },
    ],
  },
  {
    category: "School Subjects",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "English", emoji: "🔤", accepted: ["english class"] },
      { text: "Math", emoji: "➕", accepted: ["mathematics"] },
      { text: "Chinese", emoji: "🏮", accepted: ["mandarin", "guowen"] },
      { text: "PE", emoji: "🏀", accepted: ["physical education", "gym class"] },
      { text: "Science", emoji: "🧪", accepted: ["biology", "chemistry", "physics"] },
      { text: "Social Studies", emoji: "🗺️", accepted: ["history", "geography"] },
      { text: "Music", emoji: "🎵", accepted: ["music class"] },
      { text: "Art", emoji: "🎨", accepted: ["fine arts"] },
      { text: "IT", emoji: "💻", accepted: ["computer class", "technology"] },
      { text: "Home Economics", emoji: "🍳", accepted: ["cooking class"] },
    ],
  },
  {
    category: "Items in a Student's Bag",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Textbooks", emoji: "📚", accepted: ["books", "textbook"] },
      { text: "Pencil Case", emoji: "✏️", accepted: ["pencils", "pens"] },
      { text: "Water Bottle", emoji: "🍼", accepted: ["water", "thermos"] },
      { text: "Lunchbox", emoji: "🍱", accepted: ["bento box"] },
      { text: "Folder", emoji: "📂", accepted: ["folders", "files"] },
      { text: "Notebook", emoji: "📔", accepted: ["notebooks"] },
      { text: "Umbrella", emoji: "☂️", accepted: ["raincoat"] },
      { text: "Tissues", emoji: "🧻", accepted: ["tissue paper", "napkins"] },
      { text: "Calculator", emoji: "🧮" },
      { text: "Student ID", emoji: "💳", accepted: ["easycard", "id card"] },
    ],
  },
  {
    category: "Famous Taiwanese Brands",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "TSMC", emoji: "📟", accepted: ["chips", "semiconductor"] },
      { text: "ASUS", emoji: "💻", accepted: ["zenbook", "rog"] },
      { text: "Acer", emoji: "🖥️", accepted: ["computers"] },
      { text: "Giant", emoji: "🚲", accepted: ["bicycles", "bikes"] },
      { text: "HTC", emoji: "📱", accepted: ["phones", "vive"] },
      { text: "Din Tai Fung", emoji: "🥟", accepted: ["xiaolongbao"] },
      { text: "7-Eleven", emoji: "🏪", accepted: ["seven", "uni-president"] },
      { text: "Eva Air", emoji: "✈️", accepted: ["airlines"] },
      { text: "Gogoro", emoji: "🛵", accepted: ["electric scooter"] },
      { text: "Uni-President", emoji: "🍜", accepted: ["instant noodles"] },
    ],
  },
  {
    category: "Things You Find at the Beach",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Sand", emoji: "🏖️" },
      { text: "Water", emoji: "💧" },
      { text: "Seashells", emoji: "🐚", accepted: ["seashell", "shells", "shell"] },
      { text: "Sunscreen", emoji: "🧴" },
      { text: "Towel", emoji: "🧺", accepted: ["towels"] },
      { text: "Umbrella", emoji: "⛱️", accepted: ["umbrellas"] },
      { text: "Crab", emoji: "🦀", accepted: ["crabs"] },
      { text: "Seagull", emoji: "🐦", accepted: ["seagulls", "bird"] },
      { text: "Waves", emoji: "🌊", accepted: ["wave"] },
      { text: "Bucket", emoji: "🪣", accepted: ["buckets"] },
    ],
  },
  {
    category: "Pizza Toppings",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Pepperoni", emoji: "🍕", accepted: ["sausage", "ham"] },
      { text: "Mushrooms", emoji: "🍄", accepted: ["mushroom", "shroom", "enoki", "shitake"] },
      { text: "Onions", emoji: "🧅", accepted: ["onion"] },
      { text: "Any Meat", emoji: "🍗🍖🥩", accepted: ["chicken", "beef"] },
      { text: "Bacon", emoji: "🥓", accepted: ["pork"] },
      { text: "Extra Cheese", emoji: "🧀", accepted: ["cheese", "cheddar", "mozarella", "parmesan"] },
      { text: "Black Olives", emoji: "🫒", accepted: ["black olive", "olive", "olives"] },
      { text: "Green Peppers", emoji: "🫑", accepted: ["green pepper", "pepper", "red pepper", "peppers"] },
      { text: "Pineapple", emoji: "🍍", accepted: ["fruit"] },
      { text: "Chocolate", emoji: "🍫" },
    ],
  },
  {
    category: "Things in a Supermarket",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Shopping Cart", emoji: "🛒", accepted: ["shopping carts", "cart"] },
      { text: "Cashier", emoji: "🧑‍💼", accepted: ["cashiers", "Checkout Counter", "register", "person", "worker", "man", "woman", "boy", "girl", "checkout", "counter", "robot"] },
      { text: "Soap & Toileteries", emoji: "🧼🪥🫧", accepted: ["shampoo", "soap", "toothbrush", "toothpaste"] },
      { text: "Fruits", emoji: "🍎", accepted: ["fruit", "orange", "mango", "apple", "pear", "strawberry"] },
      { text: "Vegetables", emoji: "🥕", accepted: ["vegetable", "carrot", "potato", "onion", "pumpkin", "cereal", "cornflakes"] },
      { text: "Milk & Eggs", emoji: "🥛", accepted: ["milk", "egg", "eggs"] },
      { text: "Bread", emoji: "🍞", accepted: ["toast", "sandwich", "pizza"] },
      { text: "Fish & Seafood", emoji: "🐟🦀", accepted: ["crab", "sushi", "sashimi", "clam", "lobster"] },
      { text: "Electronics", emoji: "🔌💻", accepted: ["fridge", "refrigerator", "computer", "TV", "Samsung", "iPhone", "keyboard", "laptop"] },
      { text: "Meat", emoji: "🥩", accepted: ["chicken", "beef", "cow", "pork"] },
    ],
  },
  {
    category: "Weekend Activities",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Watch Movies", emoji: "🎬", accepted: ["movie", "watch Netflix", "watch Youtube", "watch TV", "movies"] },
      { text: "Play Sports", emoji: "⚽", accepted: ["play soccer", "soccer", "badminton", "swimming", "play basketball", "basketball"] },
      { text: "Go Shopping", emoji: "🛍️", accepted: ["shopping", "go to supermarket", "supermarket"] },
      { text: "Visit Friends", emoji: "🧑‍🤝‍🧑", accepted: ["play with friend"] },
      { text: "Sleep In", emoji: "😴", accepted: ["sleep"] },
      { text: "Read a Book", emoji: "📚", accepted: ["read book", "read books"] },
      { text: "Play Video Games", emoji: "🎮", accepted: ["play game", "play video game", "play games", "Roblox", "play mobile phone"] },
      { text: "Go to the Park", emoji: "🏞️", accepted: ["go to park", "walk"] },
      { text: "Clean the House", emoji: "🧹", accepted: ["clean", "sweep the floor", "mop the floor", "clean house", "clean home"]  },
      { text: "Eat Out", emoji: "🍔", accepted: ["go to the restaurant", "go to a restaurant", "go out to eat", "eat outside", "eat in a restaurant", "eat in the restaurant"] },
    ],
  },
  {
    category: "Types of Weather",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Sunny", emoji: "☀️" },
      { text: "Rainy", emoji: "🌧️", accepted: ["rain", "drizzling", "heavy rain"] },
      { text: "Cloudy", emoji: "☁️", accepted: ["overcast"] },
      { text: "Snowy", emoji: "❄️", accepted: ["snow"] },
      { text: "Windy", emoji: "💨" },
      { text: "Stormy", emoji: "⛈️", accepted: ["thunder"] },
      { text: "Foggy", emoji: "🌫️", accepted: ["misty"] },
      { text: "Hailing", emoji: "🌨️", accepted: ["ice", "icy", "blizzard"] },
      { text: "Hot", emoji: "🔥" },
      { text: "Cold", emoji: "🥶", accepted: ["freezing"] },
    ],
  },
{
  category: "Things in a Kitchen",
  difficulty: Difficulty.NotSoEasy,
  answers: [
    { text: "Fridge", emoji: "🧊", accepted: ["refrigerator", "cold box", "freezer"] },
    { text: "Stove", emoji: "🔥", accepted: ["gas stove", "cooker", "cooking fire", "fire"] },
    { text: "Sink", emoji: "💧", accepted: ["wash", "wash hands", "water place", "water"] },
    { text: "Microwave", emoji: "⚡", accepted: ["microwave oven", "heat food", "oven", "weibolu"] },
    { text: "Pot", emoji: "🍲", accepted: ["cooking pot", "pan", "wok"] },
    { text: "Plate", emoji: "🍽️", accepted: ["plates", "dish", "dishes", "fried rice"] },
    { text: "Bowl", emoji: "🥣", accepted: ["rice bowl", "soup bowl", "rice"] },
    { text: "Spoon", emoji: "🥄", accepted: ["spoons", "spooning", "soup spoon"] },
    { text: "Forks & Knives", emoji: "🍴", accepted: ["forks", "forking", "silverware", "fork", "knife"] },
    { text: "Cup", emoji: "☕", accepted: ["cups", "mug", "glass"] },
  ],
},
  {
    category: "Things That Are Round",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Ball", emoji: "🏀", accepted: ["balls", "basketball", "volleyball", "golf ball", "bowling ball"] },
        { text: "Fruit (Orange)", emoji: "🍊", accepted: ["oranges", "watermelon", "fruit"] },
        { text: "Yoyos", emoji: "🪀", accepted: ["yoyo", "yo-yo"] },
        { text: "Pizza", emoji: "🍕", accepted: ["pizzas"] },
        { text: "Coin", emoji: "🪙", accepted: ["coins", "money"] },
        { text: "Button", emoji: "🔘", accepted: ["buttons"] },
        { text: "Earth", emoji: "🌍", accepted: ["planet", "Mars"]  },
        { text: "Sun & Moon", emoji: "☀️", accepted: ["moon", "sun"]  },
        { text: "Clock", emoji: "⏰", accepted: ["clocks", "watch"] },
        { text: "Donut", emoji: "🍩", accepted: ["donuts", "pancake"] },
    ],
  },
  {
  category: "Ice Cream Flavors",
  difficulty: Difficulty.NotSoEasy,
  answers: [
    { text: "Vanilla", emoji: "🍦", accepted: ["plain", "original", "classic vanilla"] },
    { text: "Chocolate", emoji: "🍫", accepted: ["choco", "dark chocolate", "milk chocolate"] },
    { text: "Strawberry", emoji: "🍓🥭", accepted: ["berry", "strawberries", "strawberry milk", "mango", "fruit"] },
    { text: "Matcha (Green Tea)", emoji: "🍃", accepted: ["matcha", "green tea", "japanese tea", "tea"] },
    { text: "Taro", emoji: "🟣", accepted: ["yam", "purple yam", "ube"] },
    { text: "Red Bean", emoji: "🫘", accepted: ["azuki", "bean", "sweet bean", "adzuki bean"] },
    { text: "Wasabi", emoji: "🥬", accepted: ["Japanese horseradish"] },
    { text: "Peanut", emoji: "🥜", accepted: ["nut", "groundnut", "peanut butter", "crunchy peanut"] },
    { text: "Black Sesame", emoji: "⚫", accepted: ["sesame", "roasted sesame", "sesame seed", "black seed"] },
    { text: "Lychee", emoji: "🍒", accepted: ["longan", "litchi", "tropical fruit", "taiwan fruit"] },
  ],
  },

  {
  category: "Things You Do at a Party",
  difficulty: Difficulty.NotSoEasy,
  answers: [
    { text: "Eat Cake", emoji: "🎂", accepted: ["cake", "dessert", "eating cake"] },
    { text: "Dance", emoji: "💃", accepted: ["dancing", "move", "party dance"] },
    { text: "Sing Songs", emoji: "🎤", accepted: ["sing", "karaoke", "music sing", "sing song", "Happy Birthday to you", "sing Happy Birthday", "sing Birthday song"] },
    { text: "Play Games", emoji: "🎲", accepted: ["games", "play", "game time", "game"] },
    { text: "Talk to Friends", emoji: "💬", accepted: ["chat", "talk", "friends", "friend", "talk with friends"] },
    { text: "Open Presents", emoji: "🎁", accepted: ["open gifts", "gift", "presents", "present"] },
    { text: "Blow Out Candles", emoji: "🕯️", accepted: ["candles", "blow", "birthday candles", "candle"] },
    { text: "Listen to Music", emoji: "🎶", accepted: ["music", "listen", "songs"] },
    { text: "Laugh", emoji: "😄", accepted: ["smile", "happy", "giggle", "hahaha"] },
    { text: "Drink Juice", emoji: "🥤", accepted: ["juice", "drink", "punch", "soda"] },
  ],
  },
  {
    category: "Ocean Animals",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Fish", emoji: "🐠", accepted: ["fishes"] },
        { text: "Whale", emoji: "🐋", accepted: ["whales"] },
        { text: "Dolphin", emoji: "🐬", accepted: ["dolphins"] },
        { text: "Shark", emoji: "🦈", accepted: ["sharks"] },
        { text: "Octopus", emoji: "🐙", accepted: ["octopuses", "octopi"] },
        { text: "Jellyfish", emoji: "🪼", accepted: ["jellyfishes"] },
        { text: "Sea Turtle", emoji: "🐢", accepted: ["sea turtles"] },
        { text: "Starfish", emoji: "⭐", accepted: ["starfishes"] },
        { text: "Crab", emoji: "🦀", accepted: ["crabs"] },
        { text: "Seahorse", emoji: "🐠", accepted: ["seahorses"] },
    ],
  },
 {
  category: "Social Media Platforms",
  difficulty: Difficulty.NotSoEasy,
  answers: [
    { text: "YouTube", emoji: "▶️", accepted: ["yt", "youtube app", "watch video", "youtuber"] },
    { text: "Instagram", emoji: "📸", accepted: ["ig", "insta", "photo app"] },
    { text: "Facebook", emoji: "👍", accepted: ["fb", "facebook app", "meta"] },
    { text: "TikTok", emoji: "🎵", accepted: ["douyin", "tiktok app", "short video", "reels"] },
    { text: "LINE", emoji: "💬", accepted: ["line app", "chat", "message", "stickers"] },
    { text: "Discord", emoji: "🎮", accepted: ["discord app", "chat group", "voice chat"] },
    { text: "Threads", emoji: "🧵", accepted: ["thread", "meta thread", "text app"] },
    { text: "X (Twitter)", emoji: "🐦", accepted: ["twitter", "x", "tweet", "post x"] },
    { text: "Dcard", emoji: "💙", accepted: ["d card", "college app", "forum", "d-card"] },
    { text: "Reddit", emoji: "🤖", accepted: ["reddit app", "forum", "discussion", "community"] },
  ],
},
  {
  category: "Famous Cartoon Characters",
  difficulty: Difficulty.NotSoEasy,
  answers: [
    { text: "Mickey Mouse", emoji: "🐭", accepted: ["mickey", "mouse"] },
    { text: "SpongeBob SquarePants", emoji: "🧽", accepted: ["spongebob", "squarepants", "bob"] },
    { text: "Pikachu", emoji: "⚡", accepted: ["pokemon", "pika", "chu"] },
    { text: "Doraemon", emoji: "🐱", accepted: ["doraemon", "blue cat", "robot cat", "xiaodingdang"] },
    { text: "Hello Kitty", emoji: "🎀", accepted: ["kitty", "hello kitty", "cat"] },
    { text: "Tom and Jerry", emoji: "🐱🐭", accepted: ["tom", "jerry", "cat and mouse"] },
    { text: "Crayon Shin-chan", emoji: "🖍️", accepted: ["shinchan", "crayon", "shinnosuke"] },
    { text: "Snoopy", emoji: "🐶", accepted: ["snoopy", "peanuts", "white dog"] },
    { text: "Kuromi", emoji: "🐱", accepted: ["garfield", "fat cat", "orange cat"] },
    { text: "Minions", emoji: "🍌", accepted: ["minion", "banana", "yellow guy"] },
  ],
  },


  
  // Hard Difficulty
  {
    category: "Types of Pasta",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Spaghetti", emoji: "🍝" },
      { text: "Penne", emoji: "✒️" },
      { text: "Macaroni", emoji: "🧀" },
      { text: "Lasagna", emoji: " lasagna " },
      { text: "Ravioli", emoji: " ravioli " },
      { text: "Fettuccine", emoji: " fettuccine " },
      { text: "Linguine", emoji: " linguine " },
      { text: "Angel Hair", emoji: "👼" },
      { text: "Bowtie", emoji: "🎀", accepted: ["farfalle"] },
      { text: "Ziti", emoji: " ziti " },
    ],
  },

  
  {
    category: "U.S. State Capitals",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Sacramento", emoji: "🐻" },
      { text: "Austin", emoji: "⭐" },
      { text: "Tallahassee", emoji: "☀️" },
      { text: "Albany", emoji: "🏛️" },
      { text: "Columbus", emoji: "🌰" },
      { text: "Columbus", emoji: "🌰" },
      { text: "Boston", emoji: "🍵" },
      { text: "Atlanta", emoji: "🍑" },
      { text: "Denver", emoji: "🏔️" },
      { text: "Phoenix", emoji: "🌵" },
      { text: "Harrisburg", emoji: "🔔" },
    ],
  },
  {
    category: "Famous Scientists",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Albert Einstein", emoji: "🔬" },
      { text: "Isaac Newton", emoji: "🍎" },
      { text: "Marie Curie", emoji: "☢️" },
      { text: "Galileo Galilei", emoji: "🔭" },
      { text: "Charles Darwin", emoji: "🐒" },
      { text: "Nikola Tesla", emoji: "💡" },
      { text: "Stephen Hawking", emoji: "🌌" },
      { text: "Louis Pasteur", emoji: "🥛" },
      { text: "Thomas Edison", emoji: "💡" },
      { text: "Rosalind Franklin", emoji: "🧬" },
    ],
  },
  {
    category: "Parts of a Car",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Engine", emoji: "⚙️", accepted: ["engines"] },
      { text: "Wheel", emoji: "🔘", accepted: ["wheels"] },
      { text: "Steering Wheel", emoji: "☸️" },
      { text: "Brake", emoji: "🛑", accepted: ["brakes"] },
      { text: "Seat", emoji: "💺", accepted: ["seats"] },
      { text: "Door", emoji: "🚪", accepted: ["doors"] },
      { text: "Window", emoji: "🖼️", accepted: ["windows"] },
      { text: "Headlight", emoji: "💡", accepted: ["headlights"] },
      { text: "Tire", emoji: "🔘", accepted: ["tires"] },
      { text: "Exhaust Pipe", emoji: "💨" },
    ],
  },
  {
    category: "Countries in South America",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Brazil", emoji: "🇧🇷" },
      { text: "Argentina", emoji: "🇦🇷" },
      { text: "Colombia", emoji: "🇨🇴" },
      { text: "Peru", emoji: "🇵🇪" },
      { text: "Chile", emoji: "🇨🇱" },
      { text: "Venezuela", emoji: "🇻🇪" },
      { text: "Ecuador", emoji: "🇪🇨" },
      { text: "Bolivia", emoji: "🇧🇴" },
      { text: "Uruguay", emoji: "🇺🇾" },
      { text: "Paraguay", emoji: "🇵🇾" },
    ],
  },
  {
    category: "Musical Instruments in an Orchestra",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Violin", emoji: "🎻", accepted: ["violins"] },
      { text: "Cello", emoji: "🎻", accepted: ["cellos"] },
      { text: "Trumpet", emoji: "🎺", accepted: ["trumpets"] },
      { text: "Flute", emoji: "🎶", accepted: ["flutes"] },
      { text: "Clarinet", emoji: "🎶", accepted: ["clarinets"] },
      { text: "Trombone", emoji: "🎺", accepted: ["trombones"] },
      { text: "Tuba", emoji: "🎺", accepted: ["tubas"] },
      { text: "Drums", emoji: "🥁", accepted: ["drum"] },
      { text: "Piano", emoji: "🎹", accepted: ["pianos"] },
      { text: "Harp", emoji: "🎼", accepted: ["harps"] },
    ],
  },
  {
    category: "Things in a Toolbox",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Hammer", emoji: "🔨", accepted: ["hammers"] },
      { text: "Screwdriver", emoji: "🔩", accepted: ["screwdrivers"] },
      { text: "Wrench", emoji: "🔧", accepted: ["wrenches"] },
      { text: "Pliers", emoji: "🛠️" },
      { text: "Tape Measure", emoji: "📏" },
      { text: "Drill", emoji: "🔩", accepted: ["drills"] },
      { text: "Saw", emoji: "🪚", accepted: ["saws"] },
      { text: "Nails", emoji: "🔩", accepted: ["nail"] },
      { text: "Screws", emoji: "🔩", accepted: ["screw"] },
      { text: "Level", emoji: "📏", accepted: ["levels"] },
    ],
  },
  {
    category: "Famous Landmarks",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Eiffel Tower", emoji: "🗼" },
      { text: "Statue of Liberty", emoji: "🗽" },
      { text: "Great Wall of China", emoji: "🧱" },
      { text: "Colosseum", emoji: "🏛️" },
      { text: "Pyramids of Giza", emoji: "🔺", accepted: ["pyramid of giza"] },
      { text: "Taj Mahal", emoji: "🕌" },
      { text: "Machu Picchu", emoji: "🏞️" },
      { text: "Big Ben", emoji: "🕰️" },
      { text: "Sydney Opera House", emoji: "🎭" },
      { text: "Mount Rushmore", emoji: "⛰️" },
    ],
  },
  {
    category: "Planets in Our Solar System",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Mercury", emoji: "🪐" },
      { text: "Venus", emoji: "🪐" },
      { text: "Earth", emoji: "🌍" },
      { text: "Mars", emoji: "🪐" },
      { text: "Jupiter", emoji: "🪐" },
      { text: "Saturn", emoji: "🪐" },
      { text: "Uranus", emoji: "🪐" },
      { text: "Neptune", emoji: "🪐" },
      { text: "Pluto", emoji: "🪐", accepted: ["dwarf planet"] },
      { text: "Sun", emoji: "☀️", accepted: ["star"] },
    ],
  },
  {
    category: "Jobs in a Hospital",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Doctor", emoji: "👨‍⚕️" },
      { text: "Nurse", emoji: "👩‍⚕️" },
      { text: "Surgeon", emoji: "⚕️" },
      { text: "Paramedic", emoji: "🚑" },
      { text: "Receptionist", emoji: "📠" },
      { text: "Pharmacist", emoji: "💊" },
      { text: "Radiologist", emoji: "☢️" },
      { text: "Anesthesiologist", emoji: "😴" },
      { text: "Janitor", emoji: "🧹" },
      { text: "Therapist", emoji: "🛋️" },
    ],
  },
  {
    category: "Types of Dinosaurs",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Tyrannosaurus Rex", emoji: "🦖", accepted: ["t-rex"] },
      { text: "Triceratops", emoji: "🦖" },
      { text: "Stegosaurus", emoji: "🦖" },
      { text: "Velociraptor", emoji: "🦅", accepted: ["raptor"] },
      { text: "Brachiosaurus", emoji: "🦕" },
      { text: "Pterodactyl", emoji: "🦅" },
      { text: "Ankylosaurus", emoji: "🛡️" },
      { text: "Spinosaurus", emoji: "🦖" },
      { text: "Diplodocus", emoji: "🦕" },
      { text: "Allosaurus", emoji: "🦖" },
    ],
  },
  {
    category: "Greek Gods and Goddesses",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Zeus", emoji: "⚡" },
      { text: "Hera", emoji: "👑" },
      { text: "Poseidon", emoji: "🔱" },
      { text: "Hades", emoji: "💀" },
      { text: "Athena", emoji: "🦉" },
      { text: "Apollo", emoji: "☀️" },
      { text: "Artemis", emoji: "🏹" },
      { text: "Ares", emoji: "⚔️" },
      { text: "Aphrodite", emoji: "❤️" },
      { text: "Hermes", emoji: " winged sandals " },
    ],
  },
  {
    category: "World Currencies",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Dollar", emoji: "💲" },
      { text: "Euro", emoji: "💶" },
      { text: "Yen", emoji: "💴" },
      { text: "Pound", emoji: "💷" },
      { text: "Rupee", emoji: "₹" },
      { text: "Yuan", emoji: "元" },
      { text: "Won", emoji: "₩" },
      { text: "Peso", emoji: "₱" },
      { text: "Ruble", emoji: "₽" },
      { text: "Franc", emoji: "₣" },
    ],
  },
  {
    category: "Famous Authors",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "William Shakespeare", emoji: "🎭" },
      { text: "J.K. Rowling", emoji: "⚡" },
      { text: "Stephen King", emoji: "🎈" },
      { text: "Charles Dickens", emoji: "🎄" },
      { text: "Mark Twain", emoji: "🐸" },
      { text: "Jane Austen", emoji: "❤️" },
      { text: "George Orwell", emoji: "👁️" },
      { text: "Leo Tolstoy", emoji: "🕊️" },
      { text: "Agatha Christie", emoji: "🔎" },
      { text: "Edgar Allan Poe", emoji: "🐦" },
    ],
  },

  // DEATH MODE Difficulty
  {
    category: "Types of Logical Fallacies",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Ad Hominem", emoji: "🗣️" },
      { text: "Straw Man", emoji: "🌾" },
      { text: "Slippery Slope", emoji: "📉" },
      { text: "False Dichotomy", emoji: "🌓" },
      { text: "Red Herring", emoji: "🐟" },
      { text: "Appeal to Authority", emoji: "👑" },
      { text: "Circular Reasoning", emoji: "🔄" },
      { text: "Bandwagon", emoji: "🎉" },
      { text: "Hasty Generalization", emoji: "🏃" },
      { text: "Post Hoc Ergo Propter Hoc", emoji: "🐔" },
    ],
  },
  {
    category: "Characters from Shakespearean Tragedies",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Hamlet", emoji: "💀" },
      { text: "Macbeth", emoji: "👑" },
      { text: "King Lear", emoji: "👑" },
      { text: "Othello", emoji: "🎭" },
      { text: "Romeo", emoji: "❤️" },
      { text: "Juliet", emoji: "❤️" },
      { text: "Titus Andronicus", emoji: "🏛️" },
      { text: "Brutus", emoji: "🗡️" },
      { text: "Ophelia", emoji: "🌸" },
      { text: "Desdemona", emoji: "🤧" },
    ],
  },
  {
    category: "Elements on the Periodic Table (Not in the First 20)",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Iron (Fe)", emoji: "🔩" },
      { text: "Gold (Au)", emoji: "🥇" },
      { text: "Silver (Ag)", emoji: "🥈" },
      { text: "Lead (Pb)", emoji: "⛓️" },
      { text: "Uranium (U)", emoji: "⚛️" },
      { text: "Mercury (Hg)", emoji: "🌡️" },
      { text: "Copper (Cu)", emoji: "🥉" },
      { text: "Tin (Sn)", emoji: "🥫" },
      { text: "Zinc (Zn)", emoji: "🧪" },
      { text: "Platinum (Pt)", emoji: "💎" },
    ],
  },
  {
    category: "Bones in the Human Hand and Wrist",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Phalanges", emoji: "🖐️", accepted: ["phalanx"] },
      { text: "Metacarpals", emoji: "🖐️", accepted: ["metacarpal"] },
      { text: "Carpals", emoji: "🖐️", accepted: ["carpal"] },
      { text: "Scaphoid", emoji: "Bone" },
      { text: "Lunate", emoji: "Bone" },
      { text: "Triquetrum", emoji: "Bone" },
      { text: "Pisiform", emoji: "Bone" },
      { text: "Trapezium", emoji: "Bone" },
      { text: "Trapezoid", emoji: "Bone" },
      { text: "Capitate", emoji: "Bone" },
    ],
  },
  {
    category: "Programming Languages Created Before 1980",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Fortran", emoji: "🔢" },
      { text: "Lisp", emoji: "🧠" },
      { text: "COBOL", emoji: "💼" },
      { text: "ALGOL", emoji: "📐" },
      { text: "BASIC", emoji: "🏫" },
      { text: "Pascal", emoji: "👨‍🏫" },
      { text: "C", emoji: "🥉" },
      { text: "Simula", emoji: "💻" },
      { text: "APL", emoji: "📈" },
      { text: "PL/I", emoji: "💻" },
    ],
  },
  {
    category: "Nobel Prize Winners in Physics",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Marie Curie", emoji: "☢️" },
      { text: "Albert Einstein", emoji: "🔬" },
      { text: "Max Planck", emoji: "💡" },
      { text: "Niels Bohr", emoji: "⚛️" },
      { text: "Werner Heisenberg", emoji: "🤔" },
      { text: "Erwin Schrödinger", emoji: "🐈" },
      { text: "Richard Feynman", emoji: "📈" },
      { text: "Enrico Fermi", emoji: "⚛️" },
      { text: "Paul Dirac", emoji: "⚛️" },
      { text: "Hideki Yukawa", emoji: "⚛️" },
    ],
  },
  {
    category: "Ancient Greek Philosophers",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Socrates", emoji: "🤔" },
      { text: "Plato", emoji: "📖" },
      { text: "Aristotle", emoji: "👨‍🏫" },
      { text: "Pythagoras", emoji: "📐" },
      { text: "Heraclitus", emoji: "🔥" },
      { text: "Democritus", emoji: "⚛️" },
      { text: "Diogenes", emoji: "🐕" },
      { text: "Epicurus", emoji: "😊" },
      { text: "Zeno of Citium", emoji: "🏛️" },
      { text: "Thales of Miletus", emoji: "🌊" },
    ],
  },
  {
    category: "Mythical Creatures",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Dragon", emoji: "🐉" },
      { text: "Unicorn", emoji: "🦄" },
      { text: "Griffin", emoji: "🦅" },
      { text: "Phoenix", emoji: "🔥" },
      { text: "Centaur", emoji: "🐴" },
      { text: "Minotaur", emoji: "🐂" },
      { text: "Hydra", emoji: "🐍" },
      { text: "Kraken", emoji: "🐙" },
      { text: "Sphinx", emoji: "🦁" },
      { text: "Medusa", emoji: "🐍" },
    ],
  },
  {
    category: "Terms from Chess",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Checkmate", emoji: "♚" },
      { text: "Stalemate", emoji: "🤝" },
      { text: "Castling", emoji: "🏰" },
      { text: "En Passant", emoji: "♟️" },
      { text: "Pawn", emoji: "♙" },
      { text: "Rook", emoji: "♖" },
      { text: "Knight", emoji: "♘" },
      { text: "Bishop", emoji: "♗" },
      { text: "Queen", emoji: "♕" },
      { text: "King", emoji: "♔" },
    ],
  },
  {
    category: "Composers of the Baroque Period",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Johann Sebastian Bach", emoji: "🎼" },
      { text: "George Frideric Handel", emoji: "🎼" },
      { text: "Antonio Vivaldi", emoji: "🎻" },
      { text: "Claudio Monteverdi", emoji: "🎼" },
      { text: "Henry Purcell", emoji: "🎼" },
      { text: "Domenico Scarlatti", emoji: "🎹" },
      { text: "Arcangelo Corelli", emoji: "🎻" },
      { text: "Jean-Philippe Rameau", emoji: "🎼" },
      { text: "Georg Philipp Telemann", emoji: "🎼" },
      { text: "Johann Pachelbel", emoji: "🎼" },
    ],
  },
  {
    category: "Subatomic Particles",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Proton", emoji: "⚛️" },
      { text: "Neutron", emoji: "⚛️" },
      { text: "Electron", emoji: "⚡" },
      { text: "Quark", emoji: "q" },
      { text: "Lepton", emoji: "ℓ" },
      { text: "Boson", emoji: "B" },
      { text: "Neutrino", emoji: "ν" },
      { text: "Muon", emoji: "μ" },
      { text: "Tau", emoji: "τ" },
      { text: "Gluon", emoji: "g" },
    ],
  },
  {
    category: "Branches of Philosophy",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Metaphysics", emoji: "🌌" },
      { text: "Epistemology", emoji: "🧠" },
      { text: "Ethics", emoji: "😇" },
      { text: "Aesthetics", emoji: "🎨" },
      { text: "Logic", emoji: "🔗" },
      { text: "Political Philosophy", emoji: "🏛️" },
      { text: "Existentialism", emoji: "🤔" },
      { text: "Stoicism", emoji: "😐" },
      { text: "Utilitarianism", emoji: "⚖️" },
      { text: "Phenomenology", emoji: "👁️" },
    ],
  },
];
