import { Difficulty, GameData } from './types';

export const gameData: GameData[] = [
  // Easy Difficulty
  {
    category: "Colors of the Rainbow",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Red", emoji: "🔴" },
      { text: "Orange", emoji: "🟠" },
      { text: "Yellow", emoji: "🟡" },
      { text: "Green", emoji: "🟢" },
      { text: "Blue", emoji: "🔵" },
      { text: "Indigo", emoji: "🟣" },
      { text: "Violet", emoji: "💜" },
      { text: "Purple", emoji: "🍇" },
      { text: "Pink", emoji: "🌸" },
      { text: "Brown", emoji: "🟤" },
    ],
  },
  {
    category: "Things in a Classroom",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Desk", emoji: "🪑" },
      { text: "Chair", emoji: "🪑" },
      { text: "Blackboard", emoji: "칠판" },
      { text: "Chalk", emoji: "✍️" },
      { text: "Book", emoji: "📖" },
      { text: "Pencil", emoji: "✏️" },
      { text: "Teacher", emoji: "🧑‍🏫" },
      { text: "Student", emoji: "🧑‍🎓" },
      { text: "Whiteboard", emoji: "📝" },
      { text: "Computer", emoji: "💻" },
    ],
  },
  {
    category: "Types of Fruit",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Apple", emoji: "🍎" },
      { text: "Banana", emoji: "🍌" },
      { text: "Orange", emoji: "🍊" },
      { text: "Grapes", emoji: "🍇" },
      { text: "Strawberry", emoji: "🍓" },
      { text: "Watermelon", emoji: "🍉" },
      { text: "Pineapple", emoji: "🍍" },
      { text: "Mango", emoji: "🥭" },
      { text: "Blueberry", emoji: "🫐" },
      { text: "Peach", emoji: "🍑" },
    ],
  },
  {
    category: "Farm Animals",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Cow", emoji: "🐮" },
      { text: "Pig", emoji: "🐷" },
      { text: "Chicken", emoji: "🐔" },
      { text: "Horse", emoji: "🐴" },
      { text: "Sheep", emoji: "🐑" },
      { text: "Goat", emoji: "🐐" },
      { text: "Duck", emoji: "🦆" },
      { text: "Dog", emoji: "🐶" },
      { text: "Cat", emoji: "🐱" },
      { text: "Donkey", emoji: "🫏" },
    ],
  },
  {
    category: "Things You Wear",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Shirt", emoji: "👕" },
      { text: "Pants", emoji: "👖" },
      { text: "Shoes", emoji: "👟" },
      { text: "Socks", emoji: "🧦" },
      { text: "Hat", emoji: "🧢" },
      { text: "Jacket", emoji: "🧥" },
      { text: "Dress", emoji: "👗" },
      { text: "Skirt", emoji: "🎽" },
      { text: "Gloves", emoji: "🧤" },
      { text: "Scarf", emoji: "🧣" },
    ],
  },
  {
    category: "Breakfast Foods",
    difficulty: Difficulty.Easy,
    answers: [
      { text: "Cereal", emoji: "🥣" },
      { text: "Eggs", emoji: "🍳" },
      { text: "Pancakes", emoji: "🥞" },
      { text: "Bacon", emoji: "🥓" },
      { text: "Toast", emoji: "🍞" },
      { text: "Sausage", emoji: "🌭" },
      { text: "Waffles", emoji: "🧇" },
      { text: "Oatmeal", emoji: "🥣" },
      { text: "Yogurt", emoji: "🍦" },
      { text: "Milk", emoji: "🥛" },
    ],
  },
  {
    category: "Zoo Animals",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Lion", emoji: "🦁" },
        { text: "Tiger", emoji: "🐯" },
        { text: "Elephant", emoji: "🐘" },
        { text: "Monkey", emoji: "🐵" },
        { text: "Giraffe", emoji: "🦒" },
        { text: "Zebra", emoji: "🦓" },
        { text: "Bear", emoji: "🐻" },
        { text: "Penguin", emoji: "🐧" },
        { text: "Kangaroo", emoji: "🦘" },
        { text: "Hippo", emoji: "🦛" },
    ],
  },
  {
    category: "Things in the Sky",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Sun", emoji: "☀️" },
        { text: "Moon", emoji: "🌙" },
        { text: "Stars", emoji: "⭐" },
        { text: "Clouds", emoji: "☁️" },
        { text: "Airplane", emoji: "✈️" },
        { text: "Bird", emoji: "🐦" },
        { text: "Kite", emoji: "🪁" },
        { text: "Rainbow", emoji: "🌈" },
        { text: "Helicopter", emoji: "🚁" },
        { text: "Rocket", emoji: "🚀" },
    ],
  },
  {
    category: "Shapes",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Circle", emoji: "⭕" },
        { text: "Square", emoji: "⬜" },
        { text: "Triangle", emoji: "🔼" },
        { text: "Rectangle", emoji: "▭" },
        { text: "Star", emoji: "⭐" },
        { text: "Heart", emoji: "❤️" },
        { text: "Oval", emoji: "🥚" },
        { text: "Diamond", emoji: "💎" },
        { text: "Pentagon", emoji: "⬠" },
        { text: "Hexagon", emoji: "⬡" },
    ],
  },
  {
    category: "Types of Drinks",
    difficulty: Difficulty.Easy,
    answers: [
        { text: "Water", emoji: "💧" },
        { text: "Milk", emoji: "🥛" },
        { text: "Juice", emoji: "🧃" },
        { text: "Soda", emoji: "🥤" },
        { text: "Lemonade", emoji: "🍋" },
        { text: "Tea", emoji: "🍵" },
        { text: "Coffee", emoji: "☕" },
        { text: "Hot Chocolate", emoji: "🍫" },
        { text: "Smoothie", emoji: "🍓" },
        { text: "Milkshake", emoji: "🥤" },
    ],
  },

  // Not-so-easy Difficulty
  {
    category: "Things You Find at the Beach",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Sand", emoji: "🏖️" },
      { text: "Water", emoji: "💧" },
      { text: "Seashells", emoji: "🐚" },
      { text: "Sunscreen", emoji: "🧴" },
      { text: "Towel", emoji: "🧺" },
      { text: "Umbrella", emoji: "⛱️" },
      { text: "Crab", emoji: "🦀" },
      { text: "Seagull", emoji: "🐦" },
      { text: "Waves", emoji: "🌊" },
      { text: "Bucket", emoji: "🪣" },
    ],
  },
  {
    category: "Pizza Toppings",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Pepperoni", emoji: "🍕" },
      { text: "Mushrooms", emoji: "🍄" },
      { text: "Onions", emoji: "🧅" },
      { text: "Sausage", emoji: "🌭" },
      { text: "Bacon", emoji: "🥓" },
      { text: "Extra Cheese", emoji: "🧀" },
      { text: "Black Olives", emoji: "🫒" },
      { text: "Green Peppers", emoji: "🫑" },
      { text: "Pineapple", emoji: "🍍" },
      { text: "Spinach", emoji: "🥬" },
    ],
  },
  {
    category: "Things in a Supermarket",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Shopping Cart", emoji: "🛒" },
      { text: "Cashier", emoji: "🧑‍💼" },
      { text: "Aisle", emoji: "🚶" },
      { text: "Fruits", emoji: "🍎" },
      { text: "Vegetables", emoji: "🥕" },
      { text: "Milk", emoji: "🥛" },
      { text: "Bread", emoji: "🍞" },
      { text: "Cereal", emoji: "🥣" },
      { text: "Checkout Counter", emoji: "🧾" },
      { text: "Meat", emoji: "🥩" },
    ],
  },
  {
    category: "Weekend Activities",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Watch Movies", emoji: "🎬" },
      { text: "Play Sports", emoji: "⚽" },
      { text: "Go Shopping", emoji: "🛍️" },
      { text: "Visit Friends", emoji: "🧑‍🤝‍🧑" },
      { text: "Sleep In", emoji: "😴" },
      { text: "Read a Book", emoji: "📚" },
      { text: "Play Video Games", emoji: "🎮" },
      { text: "Go to the Park", emoji: "🏞️" },
      { text: "Clean the House", emoji: "🧹" },
      { text: "Eat Out", emoji: "🍔" },
    ],
  },
  {
    category: "Types of Weather",
    difficulty: Difficulty.NotSoEasy,
    answers: [
      { text: "Sunny", emoji: "☀️" },
      { text: "Rainy", emoji: "🌧️" },
      { text: "Cloudy", emoji: "☁️" },
      { text: "Snowy", emoji: "❄️" },
      { text: "Windy", emoji: "💨" },
      { text: "Stormy", emoji: "⛈️" },
      { text: "Foggy", emoji: "🌫️" },
      { text: "Hailing", emoji: "🌨️" },
      { text: "Hot", emoji: "🔥" },
      { text: "Cold", emoji: "🥶" },
    ],
  },
  {
    category: "Things in a Kitchen",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Stove", emoji: "🔥" },
        { text: "Refrigerator", emoji: "🧊" },
        { text: "Sink", emoji: "💧" },
        { text: "Microwave", emoji: "⚡" },
        { text: "Oven", emoji: "🍞" },
        { text: "Toaster", emoji: "🍞" },
        { text: "Blender", emoji: "🍹" },
        { text: "Plate", emoji: "🍽️" },
        { text: "Fork", emoji: "🍴" },
        { text: "Spoon", emoji: "🥄" },
    ],
  },
  {
    category: "Things That Are Round",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Ball", emoji: "🏀" },
        { text: "Orange", emoji: "🍊" },
        { text: "Wheel", emoji: "☸️" },
        { text: "Pizza", emoji: "🍕" },
        { text: "Coin", emoji: "🪙" },
        { text: "Button", emoji: "🔘" },
        { text: "Earth", emoji: "🌍" },
        { text: "Sun", emoji: "☀️" },
        { text: "Clock", emoji: "⏰" },
        { text: "Donut", emoji: "🍩" },
    ],
  },
  {
    category: "Ice Cream Flavors",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Vanilla", emoji: "🍦" },
        { text: "Chocolate", emoji: "🍫" },
        { text: "Strawberry", emoji: "🍓" },
        { text: "Mint Chocolate Chip", emoji: "🍃" },
        { text: "Cookie Dough", emoji: "🍪" },
        { text: "Rocky Road", emoji: "🍫" },
        { text: "Butter Pecan", emoji: "🥜" },
        { text: "Cookies and Cream", emoji: "🍪" },
        { text: "Neapolitan", emoji: "🍦" },
        { text: "Pistachio", emoji: "🟢" },
    ],
  },
  {
    category: "Things You Do at a Party",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Eat Cake", emoji: "🎂" },
        { text: "Dance", emoji: "💃" },
        { text: "Sing", emoji: "🎤" },
        { text: "Play Games", emoji: "🎲" },
        { text: "Talk to Friends", emoji: "💬" },
        { text: "Open Presents", emoji: "🎁" },
        { text: "Blow out Candles", emoji: "🕯️" },
        { text: "Listen to Music", emoji: "🎶" },
        { text: "Laugh", emoji: "😄" },
        { text: "Drink Punch", emoji: "🥤" },
    ],
  },
  {
    category: "Ocean Animals",
    difficulty: Difficulty.NotSoEasy,
    answers: [
        { text: "Fish", emoji: "🐠" },
        { text: "Whale", emoji: "🐋" },
        { text: "Dolphin", emoji: "🐬" },
        { text: "Shark", emoji: "🦈" },
        { text: "Octopus", emoji: "🐙" },
        { text: "Jellyfish", emoji: "🪼" },
        { text: "Sea Turtle", emoji: "🐢" },
        { text: "Starfish", emoji: "⭐" },
        { text: "Crab", emoji: "🦀" },
        { text: "Seahorse", emoji: "🐠" },
    ],
  },

  // Hard Difficulty
  {
    category: "U.S. State Capitals",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Sacramento", emoji: "🐻" },
      { text: "Austin", emoji: "⭐" },
      { text: "Tallahassee", emoji: "☀️" },
      { text: "Albany", emoji: "🏛️" },
      { text: "Columbus", emoji: "🌰" },
      { text: "Boston", emoji: "🍵" },
      { text: "Atlanta", emoji: "🍑" },
      { text: "Denver", emoji: "🏔️" },
      { text: "Phoenix", emoji: "🌵" },
      { text: "Harrisburg", emoji: "🔔" },
    ],
  },
  {
    category: "Famous Scientists",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Albert Einstein", emoji: "🔬" },
      { text: "Isaac Newton", emoji: "🍎" },
      { text: "Marie Curie", emoji: "☢️" },
      { text: "Galileo Galilei", emoji: "🔭" },
      { text: "Charles Darwin", emoji: "🐒" },
      { text: "Nikola Tesla", emoji: "💡" },
      { text: "Stephen Hawking", emoji: "🌌" },
      { text: "Louis Pasteur", emoji: "🥛" },
      { text: "Thomas Edison", emoji: "💡" },
      { text: "Rosalind Franklin", emoji: "🧬" },
    ],
  },
  {
    category: "Parts of a Car",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Engine", emoji: "⚙️" },
      { text: "Wheel", emoji: "🔘" },
      { text: "Steering Wheel", emoji: "☸️" },
      { text: "Brake", emoji: "🛑" },
      { text: "Seat", emoji: "💺" },
      { text: "Door", emoji: "🚪" },
      { text: "Window", emoji: "🖼️" },
      { text: "Headlight", emoji: "💡" },
      { text: "Tire", emoji: "🔘" },
      { text: "Exhaust Pipe", emoji: "💨" },
    ],
  },
  {
    category: "Countries in South America",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Brazil", emoji: "🇧🇷" },
      { text: "Argentina", emoji: "🇦🇷" },
      { text: "Colombia", emoji: "🇨🇴" },
      { text: "Peru", emoji: "🇵🇪" },
      { text: "Chile", emoji: "🇨🇱" },
      { text: "Venezuela", emoji: "🇻🇪" },
      { text: "Ecuador", emoji: "🇪🇨" },
      { text: "Bolivia", emoji: "🇧🇴" },
      { text: "Uruguay", emoji: "🇺🇾" },
      { text: "Paraguay", emoji: "🇵🇾" },
    ],
  },
  {
    category: "Musical Instruments in an Orchestra",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Violin", emoji: "🎻" },
      { text: "Cello", emoji: "🎻" },
      { text: "Trumpet", emoji: "🎺" },
      { text: "Flute", emoji: "🎶" },
      { text: "Clarinet", emoji: "🎶" },
      { text: "Trombone", emoji: "🎺" },
      { text: "Tuba", emoji: "🎺" },
      { text: "Drums", emoji: "🥁" },
      { text: "Piano", emoji: "🎹" },
      { text: "Harp", emoji: "🎼" },
    ],
  },
  {
    category: "Things in a Toolbox",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Hammer", emoji: "🔨" },
      { text: "Screwdriver", emoji: "🔩" },
      { text: "Wrench", emoji: "🔧" },
      { text: "Pliers", emoji: "🛠️" },
      { text: "Tape Measure", emoji: "📏" },
      { text: "Drill", emoji: "🔩" },
      { text: "Saw", emoji: "🪚" },
      { text: "Nails", emoji: "🔩" },
      { text: "Screws", emoji: "🔩" },
      { text: "Level", emoji: "📏" },
    ],
  },
  {
    category: "Famous Landmarks",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Eiffel Tower", emoji: "🗼" },
      { text: "Statue of Liberty", emoji: "🗽" },
      { text: "Great Wall of China", emoji: "🧱" },
      { text: "Colosseum", emoji: "🏛️" },
      { text: "Pyramids of Giza", emoji: "🔺" },
      { text: "Taj Mahal", emoji: "🕌" },
      { text: "Machu Picchu", emoji: "🏞️" },
      { text: "Big Ben", emoji: "🕰️" },
      { text: "Sydney Opera House", emoji: "🎭" },
      { text: "Mount Rushmore", emoji: "⛰️" },
    ],
  },
  {
    category: "Planets in Our Solar System",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Mercury", emoji: "🪐" },
      { text: "Venus", emoji: "🪐" },
      { text: "Earth", emoji: "🌍" },
      { text: "Mars", emoji: "🪐" },
      { text: "Jupiter", emoji: "🪐" },
      { text: "Saturn", emoji: "🪐" },
      { text: "Uranus", emoji: "🪐" },
      { text: "Neptune", emoji: "🪐" },
      { text: "Pluto", emoji: "🪐" },
      { text: "Sun", emoji: "☀️" },
    ],
  },
  {
    category: "Jobs in a Hospital",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Doctor", emoji: "👨‍⚕️" },
      { text: "Nurse", emoji: "👩‍⚕️" },
      { text: "Surgeon", emoji: "⚕️" },
      { text: "Paramedic", emoji: "🚑" },
      { text: "Receptionist", emoji: "📠" },
      { text: "Pharmacist", emoji: "💊" },
      { text: "Radiologist", emoji: "☢️" },
      { text: "Anesthesiologist", emoji: "😴" },
      { text: "Janitor", emoji: "🧹" },
      { text: "Therapist", emoji: "🛋️" },
    ],
  },
  {
    category: "Types of Dinosaurs",
    difficulty: Difficulty.Hard,
    answers: [
      { text: "Tyrannosaurus Rex", emoji: "🦖" },
      { text: "Triceratops", emoji: "🦖" },
      { text: "Stegosaurus", emoji: "🦖" },
      { text: "Velociraptor", emoji: "🦅" },
      { text: "Brachiosaurus", emoji: "🦕" },
      { text: "Pterodactyl", emoji: "🦅" },
      { text: "Ankylosaurus", emoji: "🛡️" },
      { text: "Spinosaurus", emoji: "🦖" },
      { text: "Diplodocus", emoji: "🦕" },
      { text: "Allosaurus", emoji: "🦖" },
    ],
  },

  // DEATH MODE Difficulty
  {
    category: "Types of Logical Fallacies",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Ad Hominem", emoji: "🗣️" },
      { text: "Straw Man", emoji: "🌾" },
      { text: "Slippery Slope", emoji: "📉" },
      { text: "False Dichotomy", emoji: "🌓" },
      { text: "Red Herring", emoji: "🐟" },
      { text: "Appeal to Authority", emoji: "👑" },
      { text: "Circular Reasoning", emoji: "🔄" },
      { text: "Bandwagon", emoji: "🎉" },
      { text: "Hasty Generalization", emoji: "🏃" },
      { text: "Post Hoc Ergo Propter Hoc", emoji: "🐔" },
    ],
  },
  {
    category: "Characters from Shakespearean Tragedies",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Hamlet", emoji: "💀" },
      { text: "Macbeth", emoji: "👑" },
      { text: "King Lear", emoji: "👑" },
      { text: "Othello", emoji: "🎭" },
      { text: "Romeo", emoji: "❤️" },
      { text: "Juliet", emoji: "❤️" },
      { text: "Titus Andronicus", emoji: "🏛️" },
      { text: "Brutus", emoji: "🗡️" },
      { text: "Ophelia", emoji: "🌸" },
      { text: "Desdemona", emoji: "🤧" },
    ],
  },
  {
    category: "Elements on the Periodic Table (Not in the First 20)",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Iron (Fe)", emoji: "🔩" },
      { text: "Gold (Au)", emoji: "🥇" },
      { text: "Silver (Ag)", emoji: "🥈" },
      { text: "Lead (Pb)", emoji: "⛓️" },
      { text: "Uranium (U)", emoji: "⚛️" },
      { text: "Mercury (Hg)", emoji: "🌡️" },
      { text: "Copper (Cu)", emoji: "🥉" },
      { text: "Tin (Sn)", emoji: "🥫" },
      { text: "Zinc (Zn)", emoji: "🧪" },
      { text: "Platinum (Pt)", emoji: "💎" },
    ],
  },
  {
    category: "Bones in the Human Hand and Wrist",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Phalanges", emoji: "🖐️" },
      { text: "Metacarpals", emoji: "🖐️" },
      { text: "Carpals", emoji: "🖐️" },
      { text: "Scaphoid", emoji: "🦴" },
      { text: "Lunate", emoji: "🦴" },
      { text: "Triquetrum", emoji: "🦴" },
      { text: "Pisiform", emoji: "🦴" },
      { text: "Trapezium", emoji: "🦴" },
      { text: "Trapezoid", emoji: "🦴" },
      { text: "Capitate", emoji: "🦴" },
    ],
  },
  {
    category: "Programming Languages Created Before 1980",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Fortran", emoji: "🔢" },
      { text: "Lisp", emoji: "🧠" },
      { text: "COBOL", emoji: "💼" },
      { text: "ALGOL", emoji: "📐" },
      { text: "BASIC", emoji: "🏫" },
      { text: "Pascal", emoji: "👨‍🏫" },
      { text: "C", emoji: "🥉" },
      { text: "Simula", emoji: "💻" },
      { text: "APL", emoji: "📈" },
      { text: "PL/I", emoji: "💻" },
    ],
  },
  {
    category: "Nobel Prize Winners in Physics",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Marie Curie", emoji: "☢️" },
      { text: "Albert Einstein", emoji: "🔬" },
      { text: "Max Planck", emoji: "💡" },
      { text: "Niels Bohr", emoji: "⚛️" },
      { text: "Werner Heisenberg", emoji: "🤔" },
      { text: "Erwin Schrödinger", emoji: "🐈" },
      { text: "Richard Feynman", emoji: "📈" },
      { text: "Enrico Fermi", emoji: "⚛️" },
      { text: "Paul Dirac", emoji: "⚛️" },
      { text: "Hideki Yukawa", emoji: "⚛️" },
    ],
  },
  {
    category: "Ancient Greek Philosophers",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Socrates", emoji: "🤔" },
      { text: "Plato", emoji: "📖" },
      { text: "Aristotle", emoji: "👨‍🏫" },
      { text: "Pythagoras", emoji: "📐" },
      { text: "Heraclitus", emoji: "🔥" },
      { text: "Democritus", emoji: "⚛️" },
      { text: "Diogenes", emoji: "🐕" },
      { text: "Epicurus", emoji: "😊" },
      { text: "Zeno of Citium", emoji: "🏛️" },
      { text: "Thales of Miletus", emoji: "🌊" },
    ],
  },
  {
    category: "Mythical Creatures",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Dragon", emoji: "🐉" },
      { text: "Unicorn", emoji: "🦄" },
      { text: "Griffin", emoji: "🦅" },
      { text: "Phoenix", emoji: "🔥" },
      { text: "Centaur", emoji: "🐴" },
      { text: "Minotaur", emoji: "🐂" },
      { text: "Hydra", emoji: "🐍" },
      { text: "Kraken", emoji: "🐙" },
      { text: "Sphinx", emoji: "🦁" },
      { text: "Medusa", emoji: "🐍" },
    ],
  },
  {
    category: "Terms from Chess",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Checkmate", emoji: "♚" },
      { text: "Stalemate", emoji: "🤝" },
      { text: "Castling", emoji: "🏰" },
      { text: "En Passant", emoji: "♟️" },
      { text: "Pawn", emoji: "♙" },
      { text: "Rook", emoji: "♖" },
      { text: "Knight", emoji: "♘" },
      { text: "Bishop", emoji: "♗" },
      { text: "Queen", emoji: "♕" },
      { text: "King", emoji: "♔" },
    ],
  },
  {
    category: "Composers of the Baroque Period",
    difficulty: Difficulty.DeathMode,
    answers: [
      { text: "Johann Sebastian Bach", emoji: "🎼" },
      { text: "George Frideric Handel", emoji: "🎼" },
      { text: "Antonio Vivaldi", emoji: "🎻" },
      { text: "Claudio Monteverdi", emoji: "🎼" },
      { text: "Henry Purcell", emoji: "🎼" },
      { text: "Domenico Scarlatti", emoji: "🎹" },
      { text: "Arcangelo Corelli", emoji: "🎻" },
      { text: "Jean-Philippe Rameau", emoji: "🎼" },
      { text: "Georg Philipp Telemann", emoji: "🎼" },
      { text: "Johann Pachelbel", emoji: "🎼" },
    ],
  },
];